### ISSUE TITLE
Wrong form action when using responders

### ISSUE THREAD

**Issue by fernandes** [orgsync/active_interaction#232]
Hi guys,

I'm trying to use Interaction with responders in a update action, so I made my controller:

```ruby
def update
  @thing = ThingUpdate.run(id: params[:id], name: params[:thing][:name])
  respond_with(@thing, location: thing_path)
end
```

and then made my interaction

```ruby
module Things
  class ThingUpdate < ActiveInteraction::Base
    # required
    integer :id
    string :name
    
    validates :name, length: { minimum: 2 }
    
    def execute
      @thing = compose(Things::ThingFind, id: id)
      @thing.update(name: name)
      @thing
    end
  end
end
```

when I first access localhost:3000/things/4/edit I got the right form tag generated by simple form

```html
<form accept-charset="UTF-8" action="/thing/4" class="form-horizontal edit_thing" id="edit_thing_4" method="post">
```

And then I post a name 'm' so _validates :name, length: { minimum: 2 }_ will make interaction invalid, and when renders the edit form again the form tag generated is:

```html
<form accept-charset="UTF-8" action="/thing/4" class="form-horizontal new_thing_update" id="new_thing_update_4">
```

Because the interaction is not persisted, and simple form consider as creating a new object ThingUpdate

Any idea on how get it working?

ps: I checked https://github.com/orgsync/active_interaction/pull/214 tried to upgrade my gem to branch: 'v2.0.0' but still not working

Thank you

**Comment by tfausak** [comment]
I think I have figured this out now. You want the `#to_model` method to return the thing you are updating. So in your case it would look something like this:

``` rb
def to_model
  @thing
end
```

If you do that, you don't need the `#persisted?` method at all. Check out [the example application](https://github.com/orgsync/active_interaction/blob/40051ef1fc5fe893d8e5c6d299cc452b52cdaf3f/example/app/interactions/things/update_thing.rb#L16-19) for a concrete example.
