### ISSUE TITLE
Better support for interactions that wrap another interaction or model.

### ISSUE THREAD

**Issue by AaronLasseigne** [orgsync/active_interaction#245]
## Goal

Reduce redundancy in interactions that wrap an underlying interaction or model. Often these are used in form objects and/or replace the CUD operations.
## Areas of Redundancy
1. Filters
2. Validation

**Comment by AaronLasseigne** [comment]
A thought I had recently is that it might be good to just create two new `compose` type methods that allow for the creation or updating of an AR model. Something like, `new_model` and `update_model`.

**Comment by tfausak** [comment]
How would that look? 

``` rb
class CreateThing < ActiveInteraction::Base
  # ...
  def execute
    new_model(Thing, inputs) # ?
  end
end
```

**Comment by AaronLasseigne** [comment]
Yup, something like that.

**Comment by tfausak** [comment]
For some reason I feel weird about adding helper methods for ActiveRecord specifically. ActiveInteraciton doesn't rely on ActiveRecord, only ActiveModel. A more general solution may be to pass an optional method parameter to `compose`. Or something else, I'm not sure. 

I think it might help to see what you'd have to do to create a new record spelled out, before we try to compress it into a helper method.

``` rb
class CreateThing < ActiveInteraction::Base
  # ...
  def execute
    thing = Thing.new(inputs)
    errors.merge!(thing) unless thing.save
    thing
  end
end
```

This assumes that the interaction inputs map one-to-one to the record's attributes. And that the record does not use protected attributes (`attr_protected` or `attr_accessible`).

**Comment by AaronLasseigne** [comment]
Right, the fact that this is a common pattern and we can provide an error mapping feature makes it worth consideration in my mind.

**Comment by tfausak** [comment]
Currently `compose` calls `run`, then checks `valid?`, then returns the `result`. If it fails, it goes with `merge_errors_onto_base` instead of just `merge!` (#87). 

`new_model` would call `new`, then check `save`, then return `itself`. If it failed, it would use `merge!`.

Would it make sense to allow setting those things when calling `compose`?

``` rb
# new_model
compose(Thing, inputs, run: :new, check: :save, return: :itself)
```

Heck, it could even take a proc.

**Comment by AaronLasseigne** [comment]
I could get on board with that.

**Comment by tfausak** [comment]
https://github.com/orgsync/active_interaction/pull/291#issuecomment-257643094

> This has been open for more than a year. We've been getting along fine without it. No one else has asked for it. I think we don't need it.
