### ISSUE TITLE
Drop support for 1.9.3

### ISSUE THREAD

**Issue by AaronLasseigne** [orgsync/active_interaction#246]
https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/

Official support for 1.9.3 stops on Feb 23 2014.

**Comment by tfausak** [comment]
https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/

**Comment by tfausak** [comment]
This may not be worth it if we want to continue supporting JRuby and Rubinius.
