### ISSUE TITLE
Collection Proxies should be implicitly coerced to arrays

### ISSUE THREAD

**Issue by aaronjensen** [orgsync/active_interaction#247]
Right now if you pass something like `MyInteraction.run foos: model.children` to an interaction that is expecting an array it will fail because `children` is a collection proxy rather than an array itself. It seems like the array filter could `to_ary` if the thing responds to it.

**Comment by tfausak** [comment]
I already fixed this in version 1.4.0. See #233. Check out [this Gist](https://gist.github.com/tfausak/72bf689fb1c9ac9bdf65) for a complete working example.

**Comment by aaronjensen** [comment]
ah, yes we saw this in the code but didn't realize it was a recent addition, we'll try upgrading, thanks.

Either way, I would say that calling `#to_ary` if it exists is the proper way to handle this in ruby. `#to_ary` is the implicit conversion to array method. If something defines that, it wants to be implicitly converted to an array. This allows you to solve this problem without class checks and covers bases you haven't thought of, including custom classes that want to be implicitly converted to arrays.

**Comment by tfausak** [comment]
I considered using `#to_ary` as a fix for #233 but ultimately decided against it. For one thing, the difference between `#to_a` and `#to_ary` is a source of confusion:

- http://stackoverflow.com/questions/9467395/whats-the-difference-between-to-a-and-to-ary-in-activerecord
- http://yehudakatz.com/2010/01/02/the-craziest-fing-bug-ive-ever-seen/
- http://tenderlovemaking.com/2011/06/28/til-its-ok-to-return-nil-from-to_ary.html

And then we'd have to support the other `#to_*` methods, which can be worse. There's `#to_h` and `#to_hash`, `#to_s` and `#to_str`, `#to_i` and `#to_int`, but `#to_sym` and `#to_f` don't have any counterparts. `#to_sym` is particularly bad:

``` rb
[].to_sym
# NoMethodError: undefined method `to_sym' for []:Array
[].to_s.to_sym
# => :[]
```

If you really want something that responds to `#to_ary`, use an interface filter.

``` rb
class Example < ActiveInteraction::Base
  interface :array_ish,
    methods: [:to_ary]
  def execute
    array_ish.to_ary
  end
end
Example.run!(array_ish: [])
# => []
```

**Comment by aaronjensen** [comment]
I don't see how any of those articles point to not supporting implicit conversion for arrays or that supporting implicit conversion for arrays necessitates implementing it for others. 

We'll just continue to monkey patch our differences in opinions. For anyone else who wants implicit conversion of arrays, this works well:

```
module FixActiveInteractionArrayCast
  def cast(value)
    value = value.to_ary if value.respond_to? :to_ary
    super value
  end
end

ActiveInteraction::ArrayFilter.prepend FixActiveInteractionArrayCast
```

**Comment by tfausak** [comment]
Those articles point out that `#to_ary` is a source of confusion, even among experienced Ruby developers. In particular, the difference between it and `#to_a` are murky at best. (As far as I can tell, implementing `#to_ary` — and having it return something other than `nil` — means that the object "is" an array, whereas implementing `#to_a` merely means that the object can be an array.)

I think that supporting `#to_ary` makes a case for supporting the other `#to_*` methods. However, that's just my opinion.

**Comment by aaronjensen** [comment]
`#to_a` is an explicit conversion method. If something responds to that non-nil, it can be explicitly converted to an array.

`#to_ary` is an implicit conversion operator. If something responds to that non-nil, it essentially is an array. This is useful for proxies or things that essentially are arrays but do not extend `Array` (you should not extend `Array` typically, but implementing `#to_ary` is usually a good workaround for this.)

`Array()` allows you to turn anything into an array. 

This is a good screencast on the topic, I'd recommend watching it if you haven't: http://www.rubytapas.com/episodes/210-Implicit-Conversion

I agree that it can be confusing to new ruby developers, but I do not think it is confusing to experienced ruby developers. The articles by experienced ruby developers that you linked to are pointing out specific nuanced behavior around how ruby uses those methods. In particular, Aaron's indicated that you can return `nil` from `#to_a` or `#to_ary` to indicate that you cannot actually be converted to an array which will save you a `#method_missing` call. Yehuda's pointed to a bug in Ruby's implementation in how it called `#method_missing` when it came to type coercion. That bug has since been fixed it seems.

The methods and their uses area clear. Experienced ruby developers use them and know what they do. 

I would suggest that every framework that does not do the right thing by using either the implicit, explicit, or `Array()` conversion operators when expecting an array is actually generating confusion. This his was in fact a source of confusion in our isolated incident the other day. One of our developers was very confused when attempting to pass something that quacks like an array *everywhere else* to an interaction and it was failing. I, being an experienced ruby developer, knew that the thing responded to `#to_ary` and should therefore have been fine to pass to something that expects an array. However when we looked at AI's code, we saw a type check (which is a smell, and ruby's solution to this particular one is implicit coercion operators). We were also confused about there not being a fix for the one type of object we passed in (a collection proxy) because we weren't experienced to know that collection proxies had a base class of `ActiveRecord::Relation` or whatever the type you're checking for in the fix is. 

I think that active_interaction being a ruby library makes the good case for implementing support for all of the implicit conversion operators that are appropriate. You actually have a method called `#cast` in each filter that does not do what the ruby language/standard lib has defined as implicit coercion.

**Comment by tfausak** [comment]
> One of our developers was very confused when attempting to pass something that quacks like an array *everywhere else* to an interaction and it was failing.

Relations don't quack like arrays, though. 

``` rb
Model.scoped.compact
# NoMethodError: undefined method `compact' for #<ActiveRecord::Relation [...]>
```

I consider the fact that they implement `#to_ary` an unfortunate mistake. Unfortunately I cannot find any official documentation for when it's appropriate to implement `#to_ary`. [This comment](https://github.com/ruby/ruby/pull/300#issuecomment-17749227) is the best I've found:

> `to_ary` should be implemented only on classes that behave exactly like an array

Consider some simpler examples from Ruby's core and standard library: `Range` and `Set`. Should they be accepted by `array` filters? Neither one of them implement `#to_ary`:

``` rb
(0..1).to_ary
# NoMethodError: undefined method `to_ary' for 0..1:Range
Set.new.to_ary
# NoMethodError: undefined method `to_ary' for #<Set: {}>
```

**Comment by aaronjensen** [comment]
> Relations don't quack like arrays, though.

Yes, you're right, I misspoke. What I meant to say is that, in my experience you can use relations in places where you would normally use arrays (because of `#to_ary` and `#to_a`). I don't think I'd consider relation's implementation of `#to_ary` a mistake because I think of it as a proxy to the array, specifically in the case of a `has_many` when it takes the form of an `*::ActiveRecord_Associations_CollectionProxy`.

That's interesting that `Set` doesn't implement `#to_ary`, but it does make some sense because the semantics of a Set are different than that of an array, whereas a relation has the same semantics (it is an ordered list of things that can have duplicates). 

At the end of the day, solving things by comparing types is less flexible and puts the onus on the library owner to change the library when the types change. For example, if Rails was to rename ActiveRecord::Relation, this would break the library in a surprising and confusing way. Imagine upgrading Rails and your tests failing because AI is saying that `foo.bars` is not an array. It sounds like you feel that is preferred to using something you feel people do not really understand. 

Any way, thanks for entertaining my suggestion and the thought provoking discussion. We'll probably upgrade and revert the monkey patch and put it back in if we run into this again. Given that it's pretty rare to implement `#to_ary` ourselves and in general, we probably won't, so as long as the class name stays the same we should be good :) Thanks!

**Comment by tfausak** [comment]
> For example, if Rails was to rename ActiveRecord::Relation, this would break the library in a surprising and confusing way.

I agree completely. The same thing could happen if they removed or changed their implementation of `#to_ary`. Those type of problems are best solved by version constraints. Rails in particular makes it hard to deal with since they don't follow any sane versioning scheme. 

> Any way, thanks for entertaining my suggestion and the thought provoking discussion.

And thank you for the discussion as well!
