### ISSUE TITLE
Support for Simple Form 3.1.0

### ISSUE THREAD

**Issue by jpowell** [orgsync/active_interaction#248]
Ran into this issue:
```
undefined method `has_attribute?' for #<ArbitraryObject:0x007ff8b35adc10>
```

`ArbitraryObject` is the class inheriting from `ActiveInteraction::Base`

Using `ActiveInteraction` version 1.4.1

**Comment by jpowell** [comment]
seems to have been introduced here: https://github.com/plataformatec/simple_form/commit/de22cb5e8cf0075b64fa350e823e302c9f1aeda5

**Comment by tfausak** [comment]
That's probably because [`#has_attribute?`](http://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods.html#method-i-has_attribute-3F) comes from ActiveRecord. ActiveInteraction only [implements ActiveModel](https://github.com/orgsync/active_interaction/blob/v1.4.1/lib/active_interaction/concerns/active_modelable.rb).

**Comment by jpowell** [comment]
Sure, but ActiveInteraction also implements `#column_for_attribute` which is in ActiveRecord.

**Comment by tfausak** [comment]
Oh, I forgot about that. I'm deferring to @AaronLasseigne.

**Comment by jpowell** [comment]
My temporary solution:
```ruby
class WatermarkInteraction < ActiveInteraction::Base
  def has_attribute?(attr)
    inputs.key?(attr)
  end
end
```

**Comment by AaronLasseigne** [comment]
I've got a fix for it in PR #252. @jpowell can you test it against your use case?

**Comment by AaronLasseigne** [comment]
@jpowell Fixed, yes?

**Comment by jpowell** [comment]
Ended up using form objects for the project, but can confirm.

--
Justin Powell

Sent from my phone

On Feb 3, 2015, at 2:13 PM, Aaron Lasseigne <notifications@github.com<mailto:notifications@github.com>> wrote:


@jpowell<https://github.com/jpowell> Fixed, yes?
