### ISSUE TITLE
Support for presupplied arguments

### ISSUE THREAD

**Issue by marten** [orgsync/active_interaction#249]
In our application, I have just implemented a wrapper for ActiveInteraction that enables you to presupply enforced parameters. That is probably awfully vague, so let's give an example (calls to `valid?` etc omitted for brevity).

Let's say an operation has some inputs you don't want to be user-supplied:

```ruby
# BlogPostController.rb
def create
  CreateComment.run!(post: blogpost, author: current_user, title: params[:comment][:title], body: params[:comment][:body])
  # if result.valid? etc etc
end
```

That's obviously not very nice, and very verbose. You could use hash merging, using reverse_merge to take care nothing can be overridden from params.

```ruby
# BlogPostController.rb
def create
  CreateComment.run!({post: blogpost, author: current_user}.reverse_merge(params[:comment]))
  # if result.valid? etc etc
end
```

## Proposal

To add a new class method `with` (or other name):

```ruby
# BlogPostController.rb
def create
  CreateComment.with(post: blogpost, author: current_user).run!(params[:comment])
  # if result.valid? etc etc
end
```

It's a fairly subtle change, but I feel that it helps communicate the intent more clearly: `with()` supplies the enforced, "static" parameters, and then the call to `run` adds the user input.

The implementation as I've done it right now (in our application) is fairly simple, `with()` returns an object that proxies `run` to the original class with the inputs merged in. I'm happy to dive in and build a pull request for this but wanted to get your opinion first.

**Comment by tfausak** [comment]
Thanks for submitting this interesting suggestion! I have a couple questions about it:

1. Can you call `.with` more than once? If so, which inputs have precedence: the first or the last? 
2. What does this buy you, other than a slightly more intention revealing name? 

I'm skeptical about the utility of this. Compare a few of the ways to get this done:

``` rb
# naive but explicit
CreateComment.run!(post: blogpost, author: current_user, title: params[:comment][:title], body: params[:comment][:body])
# using #reverse_merge
CreateComment.run!({ post: blogpost, author: current_user }.reverse_merge(params[:comment]))
# using #merge
CreateComment.run!(params[:comment].merge(post: blogpost, author: current_user))
# using .with
CreateComment.with(post: blogpost, author: current_user).run!(params[:comment])
```

Using `.with` saves you one character compared to `#merge`. I think `#merge` is well understood by Ruby developers. In fact, I read `foo.merge(bar)` more-or-less as "foo with bar (merged in)".

**Comment by AaronLasseigne** [comment]
I agree with @tfausak. I think `merge` covers this without having to introduce a library specific method. Additionally, not all interactions take user supplied input. In those cases I'm not sure what the syntax would look like.

**Comment by marten** [comment]
No problem. That was the whole point of proposing before writing a patch. In our case, we like it simply for the intention revealing aspect of it. The one example I can give that is harder with a hash merge is that when you use the interaction object as a form object, you can reuse the result of the `with()` (but again, there's acceptable plain-ruby alternatives):

```
def new
  @comment = interaction.new
end

def create
  @comment = interaction.run!(params[:comment])
end

private def interaction
  CreateComment.with(post: blogpost, author: current_user)
end
```

It's all slim benefits and I can see how it might not make sense to add complexity for the marginal gains. Anyone who wants this can easily build it into a custom superclass between their interactions and ActiveInteraction::Base, which is exactly what we'd done. Just in case anybody ever comes across this ticket and wants something copy/pastable, this is our implementation (sans tests):

```ruby
class Operation < ActiveInteraction::Base
  class PreScopedOperation
    def initialize(operation_class, scope = {})
      @operation_class = operation_class
      @scope = scope
    end

    def new(hash = {})
      @operation_class.new(hash.merge(@scope))
    end

    def run(hash = {})
      @operation_class.run(hash.merge(@scope))
    end

    def run!(hash = {})
      @operation_class.run!(hash.merge(@scope))
    end

    def with(scope)
      PreScopedOperation.new(self, scope)
    end
  end

  def self.with(scope)
    PreScopedOperation.new(self, scope)
  end

  def call
    run
  end
end
```

**Comment by tfausak** [comment]
:+1: Thanks for sharing your code!
