### ISSUE TITLE
Replace symbolic errors with new Rails 5 type errors (i.e. details)

### ISSUE THREAD

**Issue by AaronLasseigne** [orgsync/active_interaction#250]
https://cowbell-labs.com/2015-01-22-active-model-errors-details.html

Should we go ahead and change our API to match what's coming?

**Comment by tfausak** [comment]
:+1: We should see if we can use [active_model-errors_details](https://github.com/cowbell/active_model-errors_details).

**Comment by tfausak** [comment]
I'm waiting on cowbell/active_model-errors_details#1.

**Comment by tfausak** [comment]
For posterity, this is the pull request that adds this feature to Rails 5: <https://github.com/rails/rails/pull/18322>.
