### ISSUE TITLE
Editing existing object

### ISSUE THREAD

**Issue by ahmedrb** [orgsync/active_interaction#253]
I have an AR model that has some complex after_save calbacks/methods. I'd like to move the logic out into interactors but I'm not sure how to load attribute values so that form fields are correctly populated.

Is this possible with ActiveInteraction?

**Comment by AaronLasseigne** [comment]
I don't think I fully understand your question. Can you give a rough example of what you'd like to do?

**Comment by ahmedrb** [comment]
Hi Aaron,

I mean populating a form for a typical edit/update action.

If I use @company = Company.find(1) in the edit action, then the form fields are populated with existing values.  Is it possible to do the same using an interactor like this:

class EditCompany < ActiveInteraction::Base
  string :name
  string :email
end

Something like:

def edit
  @company = EditCompany.new(company: Company.find(1))
end

so that name and email fields are populated.

**Comment by tfausak** [comment]
That should be possible. Check out this example: https://github.com/orgsync/active_interaction/issues/220#issuecomment-56574824

**Comment by ahmedrb** [comment]
That's just what I was looking for. Thanks!

**Comment by tfausak** [comment]
I added a note to #219 so that in the future this will be part of the readme.
