### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by kapso** [orgsync/active_interaction#255]
```ruby
class CreateUser < ActiveInteraction::Base
  hash :user_params, default: {} do
    string :first_name, :last_name
  end

  def execute
    # ...
  end
end
```

When I run `CreateUser.run`, I get the following error - `ActiveInteraction::InvalidNestedValueError: ActiveInteraction::InvalidNestedValueError`

Is this expected behavior? I was hoping to see required validation errors for `first_name` and `last_name`

Unfortunately its unclear how Hash filters work.

**Comment by chrisgogreen** [comment]
Try with one call to string for each symbol, the example here shows: https://github.com/orgsync/active_interaction#how-do-i-define-an-interaction

```ruby

class CreateUser < ActiveInteraction::Base
  hash :user_params, default: {} do
    string :first_name
    string :last_name
  end

  def execute
    # ...
  end
end
```

**Comment by tfausak** [comment]
Hashes behave differently than other filters when it comes to defaults. Setting `default: {}` means that the default hash will be constructed using the defaults from the block. Since both of your strings are required, the default hash turns out to be invalid. There are two ways you can fix this:

1. Change `default: {}` to `default: nil`. This makes the hash optional and doesn't try to create a default hash.
2. Add a default (probably `default: ''`) to your strings. This makes the strings inside the hash optional so it can successfully create the default hash. 

Here's how they would look:

``` rb
require 'active_interaction' # 1.5.0

class CreateUser < ActiveInteraction::Base
  hash :user_params_1, default: nil do
    string :first_name, :last_name
  end

  hash :user_params_2, default: {} do
    string :first_name, :last_name, default: ''
  end

  def execute
    inputs
  end
end

CreateUser.run!
# => {:user_params_1=>nil, :user_params_2=>{:first_name=>"", :last_name=>""}}
```

**Comment by kapso** [comment]
Tried both the approaches, does not work. My requirement is that `first_name` & `last_name` are required and they are available inside `user_params` hash. I am using v1.5.0

**Comment by tfausak** [comment]
If that's the case, you don't want a default value for the hash at all. 

``` rb
class CreateUser < ActiveInteraction::Base
  hash :user_params do
    string :first_name, :last_name
  end

  def execute
    inputs
  end
end

CreateUser.run!
# ActiveInteraction::InvalidInteractionError: User params is required
CreateUser.run!(user_params: {})
# ActiveInteraction::InvalidInteractionError: User params has an invalid nested value ("first_name" => nil)
CreateUser.run!(user_params: { first_name: 'Jane' })
# ActiveInteraction::InvalidInteractionError: User params has an invalid nested value ("last_name" => nil)
CreateUser.run!(user_params: { first_name: 'Jane', last_name: 'Doe' })
# => {:user_params=>{:first_name=>"Jane", :last_name=>"Doe"}}
```

**Comment by kapso** [comment]
@tfausak Thanks. Yea those errors are a little weird, why not show "is required" message for hash params - first & last name?

**Comment by tfausak** [comment]
That is a great question! Nested error messages used to be misleading (#36). We made them better (#158), but it looks like they could be better still.

**Comment by kapso** [comment]
Yea I dont even care about if `user_params` is required or not, what I want to present to the user is that - first & last name are required ...if that makes sense

**Comment by tfausak** [comment]
If that's the case, why not make `first_name` and `last_name` top-level inputs? Something like this maybe:

``` rb
class CreateUser < ActiveInteraction::Base
  string :first_name, :last_name
  def execute
    # ...
  end
end
```

If you use it in a controller, you could do this:

``` rb
class UserController < ApplicationController
  def create
    outcome = CreateUser.run(params[:user])
    # ...
  end
end
```

**Comment by kapso** [comment]
I could :) but the use case I am dealing with - requires to send a user param hash. Basically I am sending in multiple hashes.

**Comment by AaronLasseigne** [comment]
Are you sure they should be going in as multiple hashes and not a merged hash?

**Comment by tfausak** [comment]
If they do have to be multiple hashes, I think this is the best we can do in terms of error handling:

```
# errors.symbolic
{ user_params: [:missing_nested] }

# errors.messages
{ user_params: ['is missing a nested value (first_name)'] }

# full message
User params is missing a nested value (first_name)
```

**Comment by kapso** [comment]
So our existing business logic is encapsulated inside https://github.com/collectiveidea/interactor (another great project) -- most of our existing interactors accept multiple hashes (user_params, address_params etc) in the interface (and not one merged hash). So lot of existing code is written that way. The fact the user details is nested inside `user_params` is hidden from the client (in our case API client) -- so nested error message does not make sense. A plain vanilla "First name is required" is more intuitive for the client.

I am looking into the possibility of migrating to `active_interaction` mainly coz it offers validations which is pretty sweet.

**Comment by tfausak** [comment]
I don't think we can support your use case. It's not possible in general to lift errors from inside a hash to outside it. (See #257 for why.) The error messages we generate should give you all the information you need to handle this in the controller. 

``` rb
class Example < ActiveInteraction::Base
  hash :user_params do
    string :first_name, :last_name
  end
end

outcome = Example.run(user_params: {})
puts outcome.errors.messages[:user_params]
# has an invalid nested value ("first_name" => nil)
```

**Comment by tfausak** [comment]
I'm going to close this issue. We can't support your use case. If inputs inside hashes have to keep their errors inside the hash. If they didn't, you'd have the potential for collisions. For example, what do you imagine the errors would look like here?

``` rb
class Example < ActiveInteraction::Base
  hash :a do
    boolean :x
  end
  hash :b do
    string :x
  end

  def execute
    # ...
  end
end
```
