### ISSUE TITLE
Adding Errors

### ISSUE THREAD

**Issue by guizmaii** [orgsync/active_interaction#257]
I don't understand why when I write this in my interaction : 
```ruby
errors.add(:no_way)
```

and I have the following error : 

```
NoMethodError - undefined method `no_way'
```

I need to write this : 
```ruby
errors.add(:no_way, 'no_way')
```
in order to correctly add an error.
The ```add_sym``` method has the same behavior.

**Comment by tfausak** [comment]
This behavior actually comes [from ActiveModel](https://github.com/rails/rails/blob/v4.2.0/activemodel/lib/active_model/errors.rb#L433). In general, you can't add errors to an attribute that doesn't exist on a model. So this code will raise an error:

``` rb
class Example < ActiveInteraction::Base
  def execute
    errors.add :no_way
  end
end
Example.run!
```

While this code won't:

``` rb
class Example < ActiveInteraction::Base
  boolean :no_way
  def execute
    errors.add :no_way
  end
end
Example.run!
```

**Comment by guizmaii** [comment]
Ok. Thank you for the answer.
