### ISSUE TITLE
How to test?

### ISSUE THREAD

**Issue by LimeBlast** [orgsync/active_interaction#259]
Is there any documenation on how to unit test objects created with this gem? I'm using rspec in my project, and I'm looking for a way in which I can unit test my object in isolation.

Thanks.

**Comment by tfausak** [comment]
We don't have any documentation for testing. We use RSpec to test ActiveInteraction, so you could look at [our integration specs](https://github.com/orgsync/active_interaction/tree/v1.5.0/spec/active_interaction/integration) for some examples. But here's a simpler, more concrete example:

``` rb
require 'active_interaction' # 1.5.0
require 'rspec' # 3.2.0

class Example < ActiveInteraction::Base
  string :string

  validates :string,
    presence: true

  def execute
    string
  end
end

describe Example do
  let(:inputs) { {} }
  let(:outcome) { described_class.run(inputs) }
  let(:outcome!) { described_class.run!(inputs) }
  let(:result) { outcome.result }
  let(:errors) { outcome.errors }

  it 'type checks' do
    expect(outcome).to_not be_valid
    expect(errors).to have_key :string
    expect(errors[:string]).to include 'is required'
  end

  it 'type checks!' do
    expect { outcome! }.to raise_error ActiveInteraction::InvalidInteractionError
  end

  it 'validates' do
    inputs[:string] = ''
    expect(outcome).to_not be_valid
    expect(errors).to have_key :string
    expect(errors[:string]).to include "can't be blank"
  end

  it 'validates!' do
    inputs[:string] = ''
    expect { outcome! }.to raise_error ActiveInteraction::InvalidInteractionError
  end

  it 'executes' do
    inputs[:string] = rand.to_s
    expect(outcome).to be_valid
    expect(result).to eql inputs[:string]
  end

  it 'executes!' do
    inputs[:string] = rand.to_s
    expect { outcome! }.to_not raise_error
    expect(outcome!).to eql inputs[:string]
  end
end
```

Does that answer your question?

**Comment by LimeBlast** [comment]
Hi, thank you for your reply.

I'm very new to testing and using rspec, but I decided to give it a bash, and ended up with the following:

```ruby
class RegisterUserForm < ActiveInteraction::Base
  string :email, :password, :password_confirmation

  validates :email, presence: true
  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validate :email_uniqueness

  def execute
    User.create!(inputs)
  end

  def self.model_name
    ActiveModel::Name.new(self, nil, 'RegisterUser')
  end

  private

    def email_uniqueness
      errors.add_sym(:email, :not_unique) unless email_unique?
    end

    def email_unique?
      !User.exists?(email: email)
    end
end
```

```ruby
require 'rails_helper'

RSpec.describe RegisterUserForm do
  let(:email) { 'email@example.com' }
  let(:password) { 'password' }
  let(:password_confirmation) { 'password' }
  let(:user) { build(:user) }
  let(:user_exists?) { false }

  let(:model_name) { ActiveModel::Name.new(self, nil, 'RegisterUser') }
  let(:valid_params) { { email: email, password: password, password_confirmation: password_confirmation } }
  let(:user_class) { class_double(User).as_stubbed_const }

  before :each do
    allow(user_class).to receive(:create!).and_return(user)
    allow(user_class).to receive(:exists?).and_return(user_exists?)
  end

  it 'accepts a valid hash' do
    expect { RegisterUserForm.run!(valid_params) }.to_not raise_error
  end

  it "doesn't accept an invalid hash" do
    expect { RegisterUserForm.run!({}) }.to raise_error(ActiveInteraction::InvalidInteractionError)
  end

  it 'returns RegisterUser as the model_name' do
    expect(RegisterUserForm.model_name).to eq(model_name)
  end

  context 'when passwords do not match' do
    let(:password) { 'password1' }
    let(:password_confirmation) { 'password2' }

    it 'is invalid' do
      result = RegisterUserForm.run(valid_params)
      expect(result.valid?).to eq(false)
    end
  end

  context 'when password is too short' do
    let(:password) { '12' }
    let(:password_confirmation) { '12' }

    it 'is invalid' do
      result = RegisterUserForm.run(valid_params)
      expect(result.valid?).to eq(false)
    end
  end

  context 'when password confirmation is missing' do
    let(:password_confirmation) { '' }

    it 'is invalid' do
      result = RegisterUserForm.run(valid_params)
      expect(result.valid?).to eq(false)
    end
  end

  context 'when email is missing' do
    let(:email) { '' }

    it 'is invalid' do
      result = RegisterUserForm.run(valid_params)
      expect(result.valid?).to eq(false)
    end
  end

  context 'when email is not unique' do
    let(:user_exists?) { true }

    it 'is invalid' do
      result = RegisterUserForm.run(valid_params)
      expect(result.valid?).to eq(false)
    end
  end
end
```

... which, I think, does the job, but doesn't look at elegant as what you've created - so I'll take a proper look at your example, and see what can be imporved on mine.

Thank you.

**Comment by tfausak** [comment]
Yeah, what you have will do the job. If you're going to test a lot of interactions, you'll probably want to create [a shared example group](https://github.com/rspec/rspec-core/blob/v3.2.0/README.md#shared-examples-and-contexts). Check out [ours](https://github.com/orgsync/active_interaction/blob/v1.5.0/spec/support/interactions.rb#L13-L17) for inspiration.

**Comment by LimeBlast** [comment]
Thank you for your help.

**Comment by LimeBlast** [comment]
Hi @tfausak, sorry for coming back to this, but something about this isn't sitting right with me. I thank you very much for [your code sample](https://github.com/orgsync/active_interaction/issues/259#issuecomment-75083421), and I think I can see what you're demonstrating, but I don't think it's a very good example of real-world usage - or rather, I'm here trying to build a spec for a real world app, and I'm struggling.

Specifically (for now at least) the `it 'type checks'` and `it 'validates'` calls are confusing me. What is the best pratice for situations where you've got multiple inputs, each with different validation rules. Would all of them be put in that single call:

```ruby
it 'type checks' do
  expect(outcome).to_not be_valid
  expect(errors).to have_key :string
  expect(errors[:string]).to include 'is required'
  expect(errors).to have_key :string2
  expect(errors[:string2]).to include 'is required'
  expect(errors).to have_key :string3
  expect(errors[:string3]).to include 'is required'
end
```

or would they be split out into seperate calls:

```ruby
it 'type checks string 1' do
  expect(outcome).to_not be_valid
  expect(errors).to have_key :string
  expect(errors[:string]).to include 'is required'
end

it 'type checks string 2' do
  expect(outcome).to_not be_valid
  expect(errors).to have_key :string2
  expect(errors[:string2]).to include 'is required'
end

it 'type checks string 3' do
  expect(outcome).to_not be_valid
  expect(errors).to have_key :string3
  expect(errors[:string3]).to include 'is required'
end
```

Sorry if these are silly questions, but as this is going to be the very core of my app, I want to make sure I'm approaching it from the right direction.

**Comment by AaronLasseigne** [comment]
I believe the general wisdom with tests is that they should test only one thing. I would split them into separate calls like you have in the second example.

**Comment by LimeBlast** [comment]
Thank you @AaronLasseigne. I'm still new to testing, so I know I have a lot to learn. It just feels like a lot of work is required to test everything - maybe because it's doing so much?

I'll continue with this and see what I end up with. Thank you.

**Comment by tfausak** [comment]
It is doing a lot, but you can make it easier on yourself. I have defined a method called `expect_error` that handles all the boilerplate for me. Given all of the variables from my example earlier, this is what it might look like:

``` rb
def expect_error(input, value = nil)
  expect(outcome).to be_invalid

  case value
  when String
    expect(errors.messages).to have_key input
    expect(errors.messages[input]).to include value
  when Symbol
    expect(errors.symbolic).to have_key input
    expect(errors.symbolic[input]).to include value
  else
    expect(errors).to include input
  end
end
```

Then you can use it like this:

``` rb
expect_error :x, 'is required'
expect_error :x, :required
expect_error :x
```

**Comment by AaronLasseigne** [comment]
It's also worth nothing that the example @tfausak provided is very thorough. You may or may not need to test all of that. Testing the type checks is really there to make sure that you used the one you wanted (e.g. `string` vs `integer`). Making sure those filters are type checking correctly is our job as library maintainers. Testing them again provides some peace of mind but might be overly cautious.

A lot of knowing what to test is figuring out how important it is that the system doesn't fail at that point and what's likely to fail. Otherwise you'll end up writing twice as much test code as actual code.

**Comment by LimeBlast** [comment]
You make a good point regarding that of over testing. It's not my job to make sure that `.run` and `.run!` works - that's why I'm using gem. Instead my job is to make sure that when I pump in XYZ, I get back ACB (or whatever the specific requirements for that task is).

With this in mind, I think it's probably important for me to test the inputs (maybe not their types exactly, but that they exist), test the validation, and then test the outcomes of both valid and invalid operations.

I'm working on a couple of specs at the moment, and have a couple of ideas. If you don't mind, I'm going to work on them to completion, then I'll post my code here to get some feedback on it.

PS, I'm also working on creating some generic specs for rails controllers based on the [conventions you've outlined here](https://github.com/orgsync/active_interaction#controller) - I'm happy to share them too, if you deem them worthy enough for the readme file or something.

Gimme a couple days :) Thanks.

**Comment by LimeBlast** [comment]
As promised, this is what I've come up with so far:

https://gist.github.com/LimeBlast/48771c30a9b9fc940b3e

Opinions and feedback most welcome.

**Comment by tfausak** [comment]
Looks good. My only comment is that we generally try to avoid using stubs when testing interactions. Since they contain our most important business logic, we want to test them with real objects that hit the real database. The downside is that your tests might run slower. That's a price we're usually willing to pay. (There are ways to mitigate it. Check out [my blog post](http://taylor.fausak.me/2014/01/10/write-faster-tests-with-a-factory-context/) about speeding up specs by sharing objects.)

**Comment by LimeBlast** [comment]
That's a valid point, thank you. My only reply to that is I do have a full suite of feature tests which do hit the database. I'll see how I get on with it this this, and change it if I run into any major issues.

Cheers for your help and feedback. :beer:

**Comment by x9sim9** [comment]
As I stumbled on this thread whilst making my own shared examples I thought I would post what I came up with

RSpec.shared_examples :interaction_has_validations do |presence:, interaction: nil, params: nil|
	let(:current_interaction) { interaction || described_class }
	let(:current_params) { params || inputs }

	it "valid?" do
		expect(current_interaction.run(**current_params)).to be_valid
	end

	presence.each do |current|
		it "not valid without #{current}" do
			current_params[current] = nil

			expect(current_interaction.run(**current_params)).to_not be_valid
		end
	end
end

RSpec.shared_examples :interaction_has_fields do |fields:, interaction: nil, params: nil|
	let(:current_interaction) { interaction || described_class }
	let(:current_params) { params || inputs }

	it "valid?" do
		expect(current_interaction.run(**current_params)).to be_valid
	end

	fields.each do |current|
		it "has field :#{current}" do
			current_params[current] = nil

			expect(current_interaction.run(**current_params).inputs).to have_key current
		end
	end
end
