### ISSUE TITLE
Rename model filter to object filter?

### ISSUE THREAD

**Issue by tfausak** [orgsync/active_interaction#264]
The model filter doesn't really define a model. It defines an object. More specifically, it defines an instance of a class. For instance, if you want a `Proc` input, you have to do this:

``` rb
model :proc
```

That doesn't really make sense to me. I think this would be better:

``` rb
object :proc
```

I think we ended up with `model` because we usually use this filter for ActiveModel objects. But it's designed to work with anything. I think we should change the name to reflect that.

**Comment by AaronLasseigne** [comment]
```rb
> Class.ancestors
=> [Class, Module, Object, Kernel, BasicObject]
```

It also seems to more clearly indicate the fact that it can be used for modules.

**Comment by AaronLasseigne** [comment]
I think this is a good change.
