### ISSUE TITLE
Flash messaging

### ISSUE THREAD

**Issue by DangerDawson** [orgsync/active_interaction#268]
Just a thought..

Say I have a situation where I want to set the flash message based on a conditional ( Business Logic ), traditionally this has been set in the controller although do you think it is bad practice to move this into a interaction?

D

**Comment by tfausak** [comment]
I don't think setting flash messages in an interaction is a good practice. Yes, it is business logic, but it's specific to the request. 

Does that answer your question? If not, can you provide a more concrete example?

**Comment by DangerDawson** [comment]
Basically we use a flash message to trigger a piece of javascript in a partial which is renders a receipt page when a user pays for an item on the site ( Spree based site ), and I was trying to put the business logic somewhere.

After much thought I came to the exact same conclusion as you though.

BTW. this is a cracking gem and exactly what we were after... keep up the good work!!

**Comment by tfausak** [comment]
Thanks!
