### ISSUE TITLE
Evaluate default attribute procs on #execute

### ISSUE THREAD

**Issue by hadronzoo** [orgsync/active_interaction#269]
Defaults attributes are evaluated on class definition, even if the default is a proc or a lambda. It would be useful and less surprising if default procs were executed when `run!` was called rather than when the interaction was required.

**Comment by AaronLasseigne** [comment]
This is certainly worth some thought.

**Comment by tfausak** [comment]
Yeah, I agree. We didn't consider this when we made #141. The offending line is in [`ActiveInteraction::Base`](https://github.com/orgsync/active_interaction/blob/779ebe3c7f80d5747bbcd3ec951d6c04f60d5699/lib/active_interaction/base.rb#L172). It has been like that for a long while. I think it originally came from 6b165d5b90b4f455a0e6e65fdca26c03bd06496a.
