### ISSUE TITLE
Feature request: Populate symbolic errors in InvalidInteractionError

### ISSUE THREAD

**Issue by attilaenflick** [orgsync/active_interaction#273]
It would be great to fetch the symbolic error(s) from any InvalidInteractionError exception.

**Comment by tfausak** [comment]
I think this is a reasonable addition. Can you explain why you want it, though? Typically if you want the errors you should use `.run` instead of `.run!`.

**Comment by attilaenflick** [comment]
The desire came from a situation where we were testing using run!, but then were unable to verify that we triggered the correct error message (without resorting to string matching). We changed to use run instead as a result.

run! is practically useless for "machine consumption" whereas run allows alternate pathways via conditionals.

Having an "errors" method on the exception also allows the following, slightly less verbose, controller logic:

*What we can do today*

ExampleController#create

    def create
        outcome = Orders::CreateOrder.run(order_params)
        
        if outcome.valid?
            @order = outcome.result
            flash[:notice] = "Success"
            redirect_to order_path(@order)
        else
            flash.now[:error] = outcome.errors.full_messages.to_sentence
            render action: 'new'
        end
    end

*What we would like to do*

ExampleController#create

    def create
        outcome = Orders::CreateOrder.run!(order_params)
        @order = outcome.result
        flash[:notice] = "Success"
        redirect_to order_path(@order)
    rescue ActiveInteraction::InvalidError => e
        flash.now[:error] = e.errors.full_messages.to_sentence
        render action: 'new'
    end

**Comment by tfausak** [comment]
I understand your test use case. I think it makes more sense to use `.run` when testing. 

As for the controller, you can already do what you want. 

``` rb
rescue ActiveInteraction::InvalidInteractionError => error
  flash.new[:error] = error.message
  render action: 'new'
end
```

**Comment by attilaenflick** [comment]
Good point, thanks!
