### ISSUE TITLE
Add validations to constrain the return from execute

### ISSUE THREAD

**Issue by atteeela** [orgsync/active_interaction#275]
It would be very useful to be able to constrain the return type of execute.

Ideally it can be defined in a block like so:

    class GetFavToppings < ActiveInteraction::Base
    
      returns do
         string :topping_name
         integer :weight
      end

      def execute

          prepare_return do |p|
             p.add(:topping_name, 'peppers')
             p.add(:weight, 10)
          end
      end

    end

**Comment by tfausak** [comment]
This is interesting! I like this idea. I have a few questions, though:

1. What should happen if the return value does not match the expected type? I guess adding an error to `:base` would make the most sense.
2. Invalid interactions will soon be able to return things too. (See issue #168 for some info about that.) Should those return values be type checked?

If you need this functionality now, you should be able to wrap `execute` with a contract. I am a fan of [contracts.ruby](https://github.com/egonSchiele/contracts.ruby), which would look like this:

``` rb
Contract None => Num
def execute
  42
end
```

**Comment by tfausak** [comment]
I am willing to continue discussing this with you, but I do not think that we will add this feature to ActiveInteraction. If you want this behavior, it is possible to use another library (like contracts.ruby) to get it done. ActiveInteraction is mostly concerned with validating inputs. It is common for interactions to have no useful return type at all.
