### ISSUE TITLE
Link to upgrade documents

### ISSUE THREAD

**Issue by LimeBlast** [orgsync/active_interaction#284]
I don't remember when (or, alas, where), but last week some time I came across a blog post written by someone on this team about the changes to v2 of the gem, and how to upgrade to it. I'm about ready to do this myself now, but am unable to find the article.

Can someone link to it (maybe from the read me). Thank you.

**Comment by LimeBlast** [comment]
OK, I found it now: http://taylor.fausak.me/2015/05/07/announcing-active-interaction-2/

I'm going to leave this open however, as I think there might be some benefit to having a link to this from the readme - If you disagree, just close the ticket.

Thanks.

**Comment by tfausak** [comment]
That post is also available from the somewhat more official OrgSync developer blog: http://devblog.orgsync.com/2015/05/06/announcing-active-interaction-2/

We should probably link to it from both the readme and the change log.
