### ISSUE TITLE
ActionDispatch::Http::UploadedFile broken for Rails 3.2

### ISSUE THREAD

**Issue by AaronLasseigne** [orgsync/active_interaction#286]
When #243 was merged we used `eof?` to check file filters. That method was not added to `ActionDispatch::Http::UploadedFile` until 4.0.2.

http://apidock.com/rails/v4.0.2/ActionDispatch/Http/UploadedFile/eof%3F

**Comment by AaronLasseigne** [comment]
Current workarounds include:

Go straight to the temp file:
```ruby
file_filter_name: (file = params[:file]) && file.tempfile
```

Pass the upload as an object:
```ruby
object :file_filter_name,
  class: ActionDispatch::Http::UploadedFile
```

**Comment by tfausak** [comment]
ActionDispatch's uploaded file only has a few methods in [version 3.2.0](https://github.com/rails/rails/blob/v3.2.0/actionpack/lib/action_dispatch/http/upload.rb):

- original_filename
- content_type
- tempfile
- headers
- read
- open
- path
- rewind
- size

Of those, `#rewind` seems like the most likely replacement for `#eof?`.
