### ISSUE TITLE
Conditional filters

### ISSUE THREAD

**Issue by derrickmar** [orgsync/active_interaction#293]
Is there a way in active_interaction to have conditional filters?

E.g. It would be great if these we're considered the same thing

```ruby
    AddIdentityToUser.run(user: user, identity_params: { uid: "panda@example.com", confirmed: true })
    AddIdentityToUser.run(user: user, uid: "panda@example.com", confirmed: true)
```

By doing
```ruby
    if identity_params
      hash :identity_params do
        string :uid
        string :provider, default: "email", inclusion: { in: Identity::PROVIDERS }
        boolean :confirmed, default: false
        name :name, default: nil
      end
    else
      string :uid
      string :provider, default: "email", inclusion: { in: Identity::PROVIDERS }
      boolean :confirmed, default: false
      name :name, default: nil
    end
```

I understand this functionality can be done by setting default values and validating only one exists it would be much cleaner by doing what's above.
Thank you for the help!

**Comment by tfausak** [comment]
Currently, no. And as written, this would be impossible. The conditional would be evaluated once at the class level and the resulting interaction would only know about one set of inputs or the other.

To solve this particular issue, you could [`#merge`](http://ruby-doc.org/core-2.2.2/Hash.html#method-i-merge) some hashes together. For example:

``` rb
AddIdentityToUser.run({
  uid: 'panda@example.com',
  confirmed: true
}.merge(user: user))
```

For more information and examples about merging inputs, see #249.

**Comment by tfausak** [comment]
Does `#merge` work for you, @derrickmar?

**Comment by tfausak** [comment]
I am going to close this issue. The answer to your question is "no", but I am open to trying something else if `#merge` doesn't work for you. Please reopen if that's the case.

**Comment by derrickmar** [comment]
Hey @tfausak sorry for the belated reply. I'm going to try this tonight and get back to you.
