### ISSUE TITLE
Cannot find a way to define and optional filter

### ISSUE THREAD

**Issue by xponrails** [orgsync/active_interaction#294]
Is there a way to define and optional filter?

At the moment, all filters I define in the interactor must be passed to the call method.
Yes, I can declare a filter as default: nil, but I dont' want to find it in the inputs hash (without deleting it manually).

For example, in an "update" interactor, I don't want to provide all the parameters, but only some of them.

**Comment by tfausak** [comment]
Currently it is not possible to define an input in the way that you want. I think this is the same question as issue #230. 

> If I understand your question correctly, you want `attribute: nil` to mean "update this attribute to `nil`", whereas not having the attribute at all means "don't change the value of this attribute". As far as ActiveInteraction is concerned, `nil` inputs are the same as missing inputs. 

Since this is a common use case, I think adding `raw_inputs` would be a reasonable fix. How do you feel about that?

**Comment by xponrails** [comment]
Yes, the issue is the same.

Using `raw_inputs` as explained in the linked issue is a nice workaround, but probably we then need to validate that `raw_inputs` are a subset of `inputs`.

I think that a better idea is to define an option like
`optional: true`
to all inputs that I don't want to pass to the `run` method and that I don't want to find then in the `inputs` hash.

**Comment by tfausak** [comment]
We actually used to have an optional, uh, option. We called it `allow_nil` and decided to scrap it when we realized the overlap with `default`. See #66 for some discussion about that. 

What if the predicate methods defined for inputs returned `true` if the input was given and `false` otherwise? For example:

``` rb
class Example < ActiveInteraction::Base
  integer :x,
    default: nil

  def execute
    p x?
    p x
  end
end

Example.run!
# false
# nil
Example.run!(x: nil)
# true # this is currently `false`
# nil
Example.run!(x: 3)
# true
# 3
```

I'm hesitant to add an `optional` option because it behaves weirdly with defaults. For instance, if something is optional but doesn't have a default, that means it's fine if you don't pass it at all, but passing `nil` would be an error.

**Comment by xponrails** [comment]
I think it still missing a method that similar to `inputs` that returns only the hash of given inputs.
Given inputs must be a subset of inputs

```
class UpdateUser < ActiveInteraction::Base
  object :user
  string :first_name, :last_name

  def execute
    unless user.update_attributes(given_inputs)
      errors.merge!(user.errors)
    end
    p user.first_name
    p user.last_name
    p user.unapdatable_field
    user
  end
end

User.create(first_name: 'sid', last_name: 'vicious', unapdatable_field: 'singer')

UpdateUser.run!
# sid
# vicious
# singer
UpdateUser.run!(first_name: 'johnny')
# johnny
# vicious
# singer
UpdateUser.run!(first_name: nil, last_name: 'rotten')
# nil
# rotten
# singer
UpdateUser.run!(first_name: 'steve', last_name: 'jones', unapdatable_field: 'guitarist')
# nil
# rotten
# singer
```
What do yuu think?

**Comment by tfausak** [comment]
We talked about adding this. I decided against it since you would still have to modify it in some way. Your `given_inputs` would include `user`, which I think is not what you want. That being said, you can create `given_inputs` like so:

``` rb
inputs.select { |k, _| given?(k) }.reject { |k, _| k == :user }
```

**Comment by xponrails** [comment]
Yes, you're right.
Your solution seems to be a great way to solve the issue!
The last note:
`string :first_name, :last_name` must be declared `default: nil`, right? Otherwise the Interactor raises the validation error when calling
`UpdateUser.run!(first_name: 'johnny') `

**Comment by tfausak** [comment]
I'm glad that works for you! And yes, that's right; the inputs must have `default: nil`.

**Comment by xponrails** [comment]
Thanks for your help.
I'll use it as soon it will be in master.

But I still think that having an `optional: true` attribute would have been a greater solution. Also to have a cleanest DSL.

`string :first_name #required, you must provide it; it will appear in inputs hash`
`string :last_name, default: nil #optional, it will appear in inputs hash with value nil`
`string :instrument, optional: true #optional, it appears in inputs hash only if given. can't have a default value`

**Comment by tfausak** [comment]
I see what you mean, but I still don't like that solution. One of the properties I like about `inputs` is that it has a key for each filter. Adding an `optional` option would break that.

**Comment by xponrails** [comment]
Yes. The point is that in some interactors, probabily create interactors, I'll use `inputs`. 

In update interactor I'll use `given_inputs`.  

This can be confusing :-)

**Comment by fuzziness** [comment]
+1 for avoiding confusion.

**Comment by tfausak** [comment]
@fuzziness would you be in favor of adding a `given_inputs` method? Is that what you mean by "avoiding confusion"?

**Comment by fuzziness** [comment]
my point is related to @xponrails sentence
> This can be confusing :-)

using `given_inputs` or `inputs` in a context dependent manner IMO generate more confusion than an explicitly configured behavior for inputs.
I agree that `optional` param maybe not the most elegant way, but it's far better than having different approaches.

**Comment by tfausak** [comment]
Ah, I see. I still contend that `optional` isn't the right way to do this. The difference between `default: nil` and `optional: true` is too small. 

If you want all the inputs, use `inputs` — same as always. If you only want some of the inputs, filter them yourself. That way there is no confusion; everything is explicit. 

For the record, I have two preferred methods for handling this. If there aren't too many fields, I will handle each of them explicitly.

``` rb
user.birthday = birthday if given?(:birthday)
user.bio = bio if given?(:bio)
# ...
```

If there are a lot of fields, I will assign them en masse with `#attributes=` and `#slice`.

``` rb
user.attributes = inputs
  .slice(:birthday, :bio, ...)
  .keep_if { |k, _| given?(k) }
```

Is that reasonable?
