### ISSUE TITLE
Lazy invalid defaults get silently converted to nil

### ISSUE THREAD

**Issue by tfausak** [orgsync/active_interaction#296]
I discovered that setting a default to a lazy value of the wrong type silently converts it to `nil` instead of raising an error. For example:

``` rb
class Example < ActiveInteraction::Base
  boolean :a_boolean,
    default: -> { Object.new }

  def execute
    inputs
  end
end

Example.run!
# => {:a_boolean=>nil}
```

That should be raising an `InvalidDefaultError`, as it would when `default: Object.new`.

**Comment by AaronLasseigne** [comment]
:(

**Comment by tfausak** [comment]
I probably introduced this regression in #271.

**Comment by tfausak** [comment]
In particular, I think #271 and #265 conspired to create this regression.
