### ISSUE TITLE
Object filter can't be defaulted to nil

### ISSUE THREAD

**Issue by LongMan** [orgsync/active_interaction#302]
```
class ObjectInteraction < ActiveInteraction::Base
  object :cow, default: nil
end

ObjectInteraction.run!(cow: nil)
```

raises

`ActiveInteraction::InvalidClassError: "Cow"`

**Comment by tfausak** [comment]
That error means that the class is not defined. It doesn't have anything to do with the default. For example:

``` rb
class Example < ActiveInteraction::Base
  object :cow
end

Example.run
# ActiveInteraction::InvalidClassError: "Cow"
```

If you're copying the example from the docs, you'll need to define a `Cow` class. This should do the trick:

``` rb
class Cow
end
```

**Comment by LongMan** [comment]
Thanks, misread the error! Active Interaction is smarter than me :-)

But maybe it's possible to make error name more straightforward? `Cow` is not an invalid class in that case, it's not a class at all.

**Comment by tfausak** [comment]
For sure! Changing the error class (`InvalidClassError`) would be a breaking change to our API though. What if we added an explanation to the error message? I'm thinking something like this:

```
ActiveInteraction::InvalidClassError: class "Cow" does not exist
```

**Comment by LongMan** [comment]
It will be perfect, thanks!
