### ISSUE TITLE
Froms attributes

### ISSUE THREAD

**Issue by elfassy** [orgsync/active_interaction#308]
i'd like to have something like

```ruby
class CreatePiano < ActiveInteraction::Base
  object :user  
  hash :piano do 
    string :name
  end

  def to_model
    Piano.new
  end

  # ...
end
```

this would be great in the controller where rails already nests params under `piano`. I could then do either

```ruby
CreatePiano.run piano: params[:piano], user: current_user
# or
CreatePiano.run params.merge(user: current_user)
```

The only problem is that when i try to use this in a form it doesn't see the `name` attribute because it's nested

```ruby
@piano = CreatePiano.new
```

When `to_model` is defined, wouldn't it be a good idea to use the hash attributes that match in the form by default? (because that's how rails params are going to be formatted on submit)

Thanks!

**Comment by tfausak** [comment]
If I understand your question correctly, you want `CreatePiano#name` to return `CreatePiano#piano[:name]`, right? 

``` rb
class Piano
  attr_accessor :name
end

class CreatePiano < ActiveInteraction::Base
  hash :piano do
    string :name
  end

  def to_model
    Piano.new
  end
end

CreatePiano.new(piano: { name: 'Steinway' }).name
# Expected:
#   "Steinway"
# Actual:
#   NoMethodError: undefined method `name' for #<CreatePiano:0x...>
```

**Comment by AaronLasseigne** [comment]
Are you looking for something like:

```rb
CreatePiano.run(params[:piano].merge(user: current_user))
```

**Comment by tfausak** [comment]
That's more or less what we do in [our example Rails application](https://github.com/orgsync/active_interaction/blob/v2.1.3/example/app/controllers/things_controller.rb).

**Comment by elfassy** [comment]
@tfausak yes

```ruby
CreatePiano.new(piano: { name: 'Steinway' }).name
# Expected:
#   "Steinway"
# Actual:
#   NoMethodError: undefined method `name' for #<CreatePiano:0x...>
```

It would delegate all vars to `piano` since that's the `to_model` in this case. In other words

```ruby
p = CreatePiano.new(piano: { name: 'Steinway' })
p.name == p.piano[:name] #=> true
```

or an alternative would be to have a `params` hash with this property
```ruby
class CreatePiano
  object :user  
  hash :params do
    string :name
  end

  def execute
    user.pianos.create(params)
  end
end

# And delegation would happen automatically
CreatePiano.new(params: {name: 'Steinway'}).name #=> Steinway
```

**Comment by tfausak** [comment]
What would happen if `piano` had an attribute called `user`?

**Comment by elfassy** [comment]
That would be a problem now too no?
```ruby
class CreatePiano
  object :user
  string :user
  #...
end
```
vs

```ruby
class CreatePiano
  object :user
  hash :params do
    string :user
  end
  #...
end
```

both would not work... but i see your point, one is less obvious

**Comment by tfausak** [comment]
Currently the last defined input wins. So in your example, `user` would be a string instead of an object. We should probably warn when that happens, since you usually don't want to clobber inputs.

Anyway, my point was that lifting inputs up from a hash input will clobber some inputs. And it's not really clear what's happening. Defining `#to_model` lifts inputs from some hash in your interaction? Sounds confusing. 

I think pulling the part you want out of the params is the right way to do this.

**Comment by elfassy** [comment]
You're right. Maybe reusing `hash` here is wrong. We could introduce the concept of a group of attributes:

```ruby
class CreatePiano
  object :user
  group :piano do
    string :name
  end
  #...
end
```

where the `group` is just a shorthand to easily access a group of attributes (without slicing inputs). 
In this case `name` can be accessed as `piano[:name]` or `name`. It would also be possible to assign `name` directly or via `piano` 

```
CreatePiano.run(name: 'Yamaha')` 
# and 
CreatePiano.run(piano: {name: 'Yamaha'})
# are both valid
```

**Comment by tfausak** [comment]
I really don't like that. There should be one way to get at inputs. 

Is there some problem with getting a key from the params, as both @AaronLasseigne and I have suggested?

**Comment by elfassy** [comment]
Nothing major

1) Security risk
`CreatePiano.run(params[:piano].merge(user: current_user))` there is a risk that params that are not meant to be edited by the end user can (if someone forgets to overwrite them in the merge)

2) Extra code to slice inputs
```
def piano_params
   inputs.slice(:name)
end
def execute
  Piano.create(piano_params)
end
```
