### ISSUE TITLE
Float filter does not accept empty string

### ISSUE THREAD

**Issue by krzyzak** [orgsync/active_interaction#319]
Hi there,

I run into a problem with `float` filter. 
Let’s say that I’ve got Interactor similiar to this:

```ruby
class MyInteractor < ActiveInteraction::Base
  float :my_float, default: nil

  def execute
    puts my_float
  end
end
```

It’s a rails application, and when I’m passing params to interactor, `my_float`s’ value equals to `""`
Unfortunately, instead of setting `my_float` value to nil (default), I’m getting following error:

```ruby
MyInteractor.run!(my_float: "")
=> ActiveInteraction::InvalidInteractionError: My float is not a valid float
```

Is that a bug or expected behaviour? If it’s expected behaviour, how can I fix that?

**Comment by tfausak** [comment]
This is similar to #195. This is expected behavior; the empty string is not a valid float. To treat empty strings like `nil`, you can use [a callback](https://github.com/orgsync/active_interaction/blob/v2.1.3/README.md#callbacks). I might do something like this:

``` rb
set_callback :type_check, :before do
  self.my_float = my_float.presence
end
```

**Comment by tfausak** [comment]
Does that work for you? If it doesn't, please re-open this issue.
