### ISSUE TITLE
No connection pool for ActiveRecord::Base with rspec

### ISSUE THREAD

**Issue by jwoertink** [orgsync/active_interaction#320]
I have a rails app that doesn't use a DB. It just makes API calls for all the data. I'm using version `2.1.3` of the gem. When I run my specs I get this error

```text
Failure/Error: Unable to find matching line from backtrace
     ActiveRecord::ConnectionNotEstablished:
       No connection pool for ActiveRecord::Base
     # /Users/jeremy/.rvm/gems/ruby-2.2.0@stan/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:570:in `retrieve_connection'
     # /Users/jeremy/.rvm/gems/ruby-2.2.0@stan/gems/activerecord-4.2.4/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
     # /Users/jeremy/.rvm/gems/ruby-2.2.0@stan/gems/activerecord-4.2.4/lib/active_record/connection_handling.rb:87:in `connection'
     # /Users/jeremy/.rvm/gems/ruby-2.2.0@stan/gems/activerecord-4.2.4/lib/active_record/fixtures.rb:501:in `create_fixtures'
     # /Users/jeremy/.rvm/gems/ruby-2.2.0@stan/gems/activerecord-4.2.4/lib/active_record/fixtures.rb:979:in `load_fixtures'
     # /Users/jeremy/.rvm/gems/ruby-2.2.0@stan/gems/activerecord-4.2.4/lib/active_record/fixtures.rb:952:in `setup_fixtures'
     # /Users/jeremy/.rvm/gems/ruby-2.2.0@stan/gems/activerecord-4.2.4/lib/active_record/fixtures.rb:826:in `before_setup'
```

When I comment out this gem, all my specs run fine. I've already ensured that I'm not calling anything like fixtures, and active_record/railtie isn't included anywhere.

My guess is that it sees the `with_options` method, and thinks it needs to load ActiveRecord...

**Comment by tfausak** [comment]
It's strange that ActiveInteraction would be causing this problem. We don't depend on ActiveRecord. In fact, [the array filter](https://github.com/orgsync/active_interaction/blob/v2.1.3/lib/active_interaction/filters/array_filter.rb#L64-L65) is the only thing that even references it. Also, ActiveInteraction doesn't appear in your stack trace.

Can you provide some more information? I don't know how to reproduce this. You mention `with_options`, which is part of ActiveSupport (not ActiveRecord). We don't use `with_options` anywhere.

**Comment by jwoertink** [comment]
Ah, yup. ActiveSupport. I see that now. I've never used this gem before, so still digging into this more. It's just weird that this runs fine in development and production, but in test it fails. I think one of the other devs probably added the `with_options` in here. We're using it for filtering validations like

```ruby
class AffiliateSignup < ActiveInteraction::Base
  #...
  with_options if: :check? do |r|
    r.validates :payable_to, presence: true
    r.validates :minimum_payout, presence: true
  end
  #...
end
```

I'll keep digging around. It's possible that this gem causing the issue is just a side effect of what the actual issue is. I'll report back, or even close it if I find that to be the case. Thanks!

**Comment by tfausak** [comment]
Happy to help. 

That's a great use of `with_options`, by the way!

**Comment by jwoertink** [comment]
Ok, I made a sample app https://github.com/jwoertink/rspec-interactions-test

This app gives the exact same error as my app does. Maybe I'm just missing something here?

**Comment by tfausak** [comment]
Thanks! I'm working on whittling down that app to the simplest failing case. It looks like the real problem may be with `rspec-rails`, though.

**Comment by tfausak** [comment]
Ok, I got it down to this.

``` rb
# Gemfile
source 'https://rubygems.org'
gem 'rails', '4.2.4'
gem 'active_interaction', '2.1.3'
gem 'rspec-rails', '3.3.3'
```

``` rb
# failing_spec.rb
require 'action_controller/railtie'
require 'active_interaction'
require 'rspec/rails'
RSpec.describe('x') { it('y') { pending 'z' } }
```

``` sh
> bundle install
> bundle exec rspec failing_spec.rb 
F

Failures:

  1) x y
     Failure/Error: Unable to find matching line from backtrace
     ActiveRecord::ConnectionNotEstablished:
       No connection pool for ActiveRecord::Base
     # /.../connection_adapters/abstract/connection_pool.rb:570:in `retrieve_connection'
     # /.../connection_handling.rb:113:in `retrieve_connection'
     # /.../connection_handling.rb:87:in `connection'
     # /.../fixtures.rb:501:in `create_fixtures'
     # /.../fixtures.rb:979:in `load_fixtures'
     # /.../fixtures.rb:952:in `setup_fixtures'
     # /.../fixtures.rb:826:in `before_setup'

Finished in 0.00295 seconds (files took 0.60425 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./failing_spec.rb:4 # x y
```

**Comment by jwoertink** [comment]
wow. That's so crazy. I did come across https://github.com/rspec/rspec-rails/issues/1416, but his issue was related to devise. Maybe it's still a bug somewhere in rspec-rails?

**Comment by tfausak** [comment]
I was thinking that, but I can get the problem to go away if I require ActiveInteraction *after* rspec-rails.

**Comment by jwoertink** [comment]
Ah. So maybe this https://github.com/orgsync/active_interaction/blob/6d02d130fe3378bf971a1343ee68039e5aaf94b7/lib/active_interaction/filters/array_filter.rb#L4 could be an issue then? Rails is loaded first before the test, so this is true, then rspec says "active_record is required, so let's load fixtures"

**Comment by tfausak** [comment]
If I comment out [these lines](https://github.com/orgsync/active_interaction/blob/v2.1.3/lib/active_interaction/filters/array_filter.rb#L3-L6), it works. I'm not entirely sure why that fixes it. We may not need to require ActiveRecord at all, though.

**Comment by jwoertink** [comment]
sweet! Thanks for checking in to this.
