### ISSUE TITLE
Array of hashes with string values

### ISSUE THREAD

**Issue by dmitry** [orgsync/active_interaction#325]
I have a form with translations, which I'm generating with following code:

```ruby
= f.simple_fields_for 'translations[]', translation do |ft|
  = ft.input :locale, as: :hidden
  = ft.input :name
```

In the result I'm receiving following parameters:

```ruby
{"item"=>{"translations"=>[{"locale"=>"en", "name"=>""}, {"locale"=>"es", "name"=>""}]}}
```

Is it possible to filter such attributes with active_interaction?

I know it's possible with:

```ruby
hash :translations, strip: false
```

But it's not strict enough, so I have to use strong_parameters, which I would like to reject at all in project.

Looks like logically this code should work:

```ruby
    array :translations do
      string :name
      string :locale
    end
```

But it's not, as it's returns: `attribute names in array block`.

Should I make a PR with support of hash block in array, or it's possible to solve that somehow in other way around?

**Comment by tfausak** [comment]
Does this work?

``` rb
array :translations do
  hash do
    string :locale
    string :name
  end
end
```

`array` inputs can only have one input nested underneath them. This is because every element of the array must be the same type. And the inputs nested inside arrays cannot have names because they would never be used.

**Comment by dmitry** [comment]
@tfausak thanks for the quick reply :+1:.

I've tried that in the beginning, but looks like forgot something in integration with `accepts_nested_attributes_for`. Now it perfectly works. Thanks again!

**Comment by tfausak** [comment]
No problem. Happy to help!
