### ISSUE TITLE
Example app update_thing.rb#23 will raise `Undefined method `messages' for #<Thing` if thing.save is false

### ISSUE THREAD

**Issue by jornvandebeek** [orgsync/active_interaction#328]
See [the example app's update_thing.rb](https://github.com/orgsync/active_interaction/blob/master/example/app/interactions/things/update_thing.rb#L23) and [how merge! is implemented](https://github.com/orgsync/active_interaction/blob/master/lib/active_interaction/errors.rb#L97). 

The `merge!` method expects the `other` parameter to be something that acts like an ActiveModel::Errors object. The example app passes the record itself instead of its errors though.

**Comment by tfausak** [comment]
Good find! I was able to recreate this:

``` rb
require 'active_interaction' # 2.1.4
require 'active_record' # 4.2.5

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Schema.define { create_table(:things) { |t| t.column(:name, :string) } }

class Thing < ActiveRecord::Base
  validates :name, presence: true
end

class UpdateThing < ActiveInteraction::Base
  object :thing
  string :name, default: nil
  def execute
    thing.name = name if name?
    errors.merge!(thing) unless thing.save
    thing
  end
end

UpdateThing.run!(thing: Thing.create!(name: 'Something'), name: '')
# NoMethodError: undefined method `messages' for #<Thing id: 1, name: "">
```

I think changing `thing` to `thing.errors` should be sufficient.
