### ISSUE TITLE
Release version 3?

### ISSUE THREAD

**Issue by tfausak** [orgsync/active_interaction#338]
Since #217 is going into a minor release, the only big-ticket thing associated with [the v3.0.0 milestone](https://github.com/orgsync/active_interaction/milestones/v3.0.0) is #87. #333 fixes that and is ready to go. Is there anything else we want to include with version 3? Nothing else comes to mind for me. What about you, @AaronLasseigne?

**Comment by tfausak** [comment]
I should have mentioned:

- Ruby 2.3 will be released soon (#335). We shouldn't need to make any changes for that.

- Rails 5 will be released sometime relatively soon. They don't have a set release date. [Their v5.0.0 milestone](https://github.com/rails/rails/milestones/5.0.0) currently has 75 open issues. Since there's no beta yet, I don't know if we'll need to change anything. We already switched to detailed errors (#250), so that's one less thing to worry about.

**Comment by tfausak** [comment]
I forgot about #245. I think any fix for that could go with a minor release since it would only add functionality.

**Comment by AaronLasseigne** [comment]
Give me a bit to think about what other stuff might be good to include if anything.

**Comment by AaronLasseigne** [comment]
We might want to consider dropping support for 1.9.

**Comment by tfausak** [comment]
That would have to go along with a major release. Honestly I don't mind continuing to support Ruby 1.9.3. I stand by what I said in #246.

**Comment by AaronLasseigne** [comment]
It's not a big thing but I'm wondering if we should take the opportunity.

**Comment by tfausak** [comment]
Is there anything you would like to do that you can't because of Ruby 1.9.3 compatibility? There are a few things that would be nice, but I don't have a strong opinion about them:

- Starting with Ruby 2 the default encoding is UTF-8. That would allow us to ditch the `# coding: utf-8` comments everywhere. However this doesn't really affect us since our source files are all ASCII.

- Ruby 2 introduced the `%i(...)` syntax for arrays of symbols. We could use this in literally one non-spec line of code.

- Ruby 2 introduced keyword arguments. I don't think this would affect us at all. 

I feel like we'd be dropping support for no good reason. If we wanted to do something that required Ruby >=2 I could get behind dropping support for 1.9.3.

**Comment by tfausak** [comment]
Maybe we should officially drop support for Ruby 1.9 but continue to unofficially support it. In other words, change the documentation and the gem spec, but don't make any backwards-incompatible changes to the code.

**Comment by AaronLasseigne** [comment]
The advantage being that we can then change it later without a major version bump?

**Comment by tfausak** [comment]
Yes.

**Comment by AaronLasseigne** [comment]
I'm fine with that approach.

**Comment by tfausak** [comment]
We could also take this opportunity to drop support for ActiveModel 3.2.

**Comment by AaronLasseigne** [comment]
Probably a good idea.

**Comment by tfausak** [comment]
Now that #333, #344, and #346 are finished and green, are you ready to merge them and release 3.0?

**Comment by tfausak** [comment]
We should add a note to the README about using ActiveInteraction with older versions of Ruby and Rails. Something like: 

> If you want to use ActiveInteraction with Ruby < 2.0.0 or ActiveModel < 4.0.0, use ActiveInteraction < 3.0.0.

**Comment by AaronLasseigne** [comment]
I think that's reasonable. What section?

**Comment by tfausak** [comment]
I was thinking the "Installation" section. That's where we talk about supported versions.

**Comment by AaronLasseigne** [comment]
Works for me.

**Comment by AaronLasseigne** [comment]
I've added it in #348.

**Comment by AaronLasseigne** [comment]
I've started a branch to prep for the 3.0 release. Should we wait until Rails 5 is officially out so we can make sure everything's good?

**Comment by tfausak** [comment]
I don't want to. They don't have a release date set and we already work with the beta. I think we'll be fine with respect to Rails 5.

**Comment by AaronLasseigne** [comment]
Works for me. If you're ready we can merge #348, update the release date in the changelog, and I think it's ready to go.

**Comment by tfausak** [comment]
https://rubygems.org/gems/active_interaction/versions/3.0.0
