### ISSUE TITLE
Merge change logs?

### ISSUE THREAD

**Issue by tfausak** [orgsync/active_interaction#339]
I don't like maintaining both [CHANGELOG.md](https://github.com/orgsync/active_interaction/blob/master/CHANGELOG.md) and [our releases page](https://github.com/orgsync/active_interaction/releases). I'd rather only maintain the releases page. @AaronLasseigne how do you feel about truncating CHANGELOG.md, like [this](https://github.com/tfausak/purescript-neon/blob/b292b84/CHANGELOG.md)?

**Comment by AaronLasseigne** [comment]
If we're going to move to one changelog I'd rather ditch releases than the file. The file stays as part of the repo.

**Comment by tfausak** [comment]
I like the releases page for a few reasons:

- You can easily link to the latest release. https://github.com/orgsync/active_interaction/releases/latest

- You can link to a particular release, which includes links to browse that tag and commit. https://github.com/orgsync/active_interaction/releases/tag/v2.2.0

- Each release automatically gets a link to compare it with the current master. https://github.com/orgsync/active_interaction/compare/v2.1.5...master

- The releases editor automatically links `#`s for issues/pulls and `@`s for mentions. 

- We have to make tags anyway, which means the releases page will have stuff on it. Might as well make it look pretty. 

- I never use this feature, but you can download source zips for any release. 

One thing I would like to be able to do is cut new releases without the corresponding ":briefcase: vX.Y.Z" commit. Switching to the GitHub releases page helps that considerably.

**Comment by tfausak** [comment]
What do you think about this?

**Comment by AaronLasseigne** [comment]
> One thing I would like to be able to do is cut new releases without the corresponding ":briefcase: vX.Y.Z" commit. Switching to the GitHub releases page helps that considerably. 

We still have to bump version numbers so don't we still have to do that?

**Comment by tfausak** [comment]
Yeah, it's unavoidable. What I really meant was that I want to be able to easily do that through the web UI. Like this: https://github.com/tfausak/strive/commit/8e37ee2

**Comment by AaronLasseigne** [comment]
> You can easily link to the latest release.

You can do that with the changelog: https://github.com/orgsync/active_interaction/blob/master/CHANGELOG.md#220-2015-12-18

You do make some good points.

In favor of the file version:
 1. It stays with the repo. If we move away from GitHub (unlikely I know) it would still be there. People can look at their local copy of the gem to get the changes. It just seems safer.
 2. We can make sure a changelog entry is added as part of a commit. I'd hate to miss changes.

**Comment by tfausak** [comment]
Fair counterpoints. 

- In the unlikely event that we move away from GitHub, we can recover the change log through [their API](https://developer.github.com/v3/repos/releases/#list-releases-for-a-repository). That doesn't keep it with the repo per se, but it's easy to add it back to the repo. 
  - Maybe we could write a script that automatically generates the `CHANGELOG.md` file based on the GitHub releases. It could be part of the build when Travis is building a tag. 
- I typically look at the Git diff (like [this one](https://github.com/orgsync/active_interaction/compare/v2.1.0...v2.2.0)) when writing the change log for a release.
