### ISSUE TITLE
Async Interactions

### ISSUE THREAD

**Issue by thec0keman** [orgsync/active_interaction#359]
First, thanks for a great addon.  We make heavy use of this through all of our applications, and in general we have found this to really simplify our code and provide a shared set of assumptions for the whole team.

We built a small addon that allows an individual interaction can be run async through `ActiveJob`.  It does not hack on any of the internals of Active Interaction itself so interactions are still fully functional as a synchronous service.

The architecture is pretty simple:
- a small concern which exposes some async APIs as well as some config accessors
- an active job that accepts a class Name and keyword arguments that all interactions share

We could release this as a standalone addon to this gem, but it seems useful enough that it could have real value as a part of this gem.  Would you be interesting in adding this feature and/or accepting a pull request?

Thanks!

**Comment by tfausak** [comment]
I'm happy to hear that ActiveInteraction is working well for you! 

We at OrgSync have ended up with our own way of handling interactions that should be run asynchronously. We use Resque directly, but the concept is the same as Active Job. 

I think this type of behavior should live in a separate gem. Everybody has a different way to handle async job processing. Active Job should abstract over these, but not everyone is using Active Job. 

That being said, I'm not hard set on this. I'd be interested to hear what @AaronLasseigne has to say.

**Comment by AaronLasseigne** [comment]
It's great to hear that it's working well for you.

I also think this would be good as a separate gem. The current one only depends on activemodel and I like limiting our surface area. Additionally, as @tfausak said there are different methods of handling async. Sometimes ActiveJob doesn't do everything a person might need.

Having said that, this sounds great. We could even add information to our README directing people to your extension if they need ActiveJob support.

**Comment by thec0keman** [comment]
Thanks !
