### ISSUE TITLE
Testing composed interactions?

### ISSUE THREAD

**Issue by johnreilly** [orgsync/active_interaction#366]
Hi OrgSync, I'm just getting started with active_interaction, and I'm loving it so far. Thanks so much for sharing your hard work! 

As I've been playing along, I'm noticing that I'm creating lots of composed interactions. Something like this incredibly contrived example:

```ruby
class TopLevelInteraction < ActiveInteraction::Base
  def execute
    thing = Thing.create()
    compose(CreateFoo, thing: thing)
    compose(CreateBar, thing: thing)
  end
end

class CreateFoo < ActiveInteraction::Base
  object :thing
  
  def execute
    Foo.create(thing: thing)
  end
end

class CreateBar < ActiveInteraction::Base
  object :thing
  
  def execute
    Bar.create(thing: thing)
  end
end

```

Let's say I have the `CreateFoo` and `CreateBar` interactions nicely covered by tests.

When it comes time to test `TopLevelInteraction`, I suppose I could thoroughly test it by doing something like: 

```ruby
describe TopLevelInteraction do
  it 'should create a Thing' do
    # expect that Thing is created
  end
  it 'should create a Foo' do
    # expect that Foo is created
  end
  it 'should create a Bar' do
    # expect that Bar is created
  end
end
```

This is, in a sense, how the `#compose` method itself [is being tested](https://github.com/orgsync/active_interaction/blob/5ffd85e1162b54468d541f8bf0a59f9c05cb7f01/spec/active_interaction/base_spec.rb#L352-L354) -- checking that the result of the composed interactions is correct.

But, _given that I have `CreateFoo` and `CreateBar` already tested_, it seems it would be better to just test that the composed interactions are run. Something like:

```ruby
describe TopLevelInteraction do
  it 'should create a Thing' do
    # expect that Thing is created
  end
  it 'should be composed of CreateFoo' do
    # expect that CreateFoo is run
  end
  it 'should be composed of CreateBar' do
    # expect that CreateBar is run
  end
end
```

So, a couple of questions...
1. Am I crazy to think this way? 
2. Is something like this even possible? I couldn't figure it out myself.

Any thoughts you have would be appreciated.

Thanks again for a great project! :-)

-JohnR

**Comment by tfausak** [comment]
Good questions! 

1. You are definitely not crazy to think this way! It makes a lot of sense to only test the inner interactions once. 

2. Good news: It is possible! The best way I know of to get this done is to use RSpec's mocks. Here is an example:

  ``` rb
  it 'creates a foo' do
    expect(CreateFoo).to receive(:run)
      .and_return(double(CreateFoo, valid?: true, result: Foo.new))
    described_class.run
  end
  ```

I created [a complete example](https://gist.github.com/tfausak/15ec928b1353544247cd85f96ecb9009) showing how I might test something like this. Does that help?

**Comment by johnreilly** [comment]
Thank you so much @tfausak! I just had a chance to try this out today, and it works like a charm. 

I appreciate the help! 🍻

**Comment by lulalala** [comment]
Just for future readers, maybe you need to stub a failure case:

```
  errors = ActiveModel::Errors.new(:foo)
  errors.add(:base, "foo")
  allow(CreateFoo).to receive(:run)
    .and_return(double(CreateFoo, valid?: false, errors: errors, result: Foo.new))
```

**Comment by ivdma** [comment]
If you want original behaviour you could use:

```ruby
expect(CreateFoo).to receive(:run).and_call_original
```
