### ISSUE TITLE
question on usage - defaulting of parameters for form input

### ISSUE THREAD

**Issue by shanly** [orgsync/active_interaction#369]
Not sure where best to ask questions on usage, so adding as an issue:

Extracting the params from `current_user` in controller seems smelly to me, and something I would like to push into `CreateActName`. However, only hook I can see is overriding `initialize` which also seems bit crude.

Is there a better way of doing this?

```ruby
  def new
    @act_name = CreateActName.new(
      name:  params[:name],
      email: current_user.email,
      phone: current_user.phone,
    )
  end
```

**Comment by tfausak** [comment]
I think that's fine. What about it do you not like? You could pass the entire `current_user` into `CreateActName` if you don't want to pull specific fields from it.

**Comment by shanly** [comment]
My main driver with active_interaction was to push all business logic out of controller. This is a simple default shown here but the rules will likely become more complex. 

If this happens would definitely like to move it into `CreateActName` and can only see overriding `initialize` on `CreateActName` as been the option.

As it is right now its not causing me much angst - just seeing if I am missing some other hooks / approaches for defaulting form values based on business logic.

Thanks for the quick answer.

**Comment by tfausak** [comment]
You can make defaults depend on other inputs. See [this section](https://github.com/orgsync/active_interaction/blob/v3.2.0/README.md#defaults) of the documentation. That means that if you passed the entire `current_user` in, you could default the `email` input to `current_user.email`. Is that what you're after?

**Comment by shanly** [comment]
Ok  that sounds like it will work - thanks.

Just as an aside, I thought below might work - as a guess.

```
  def to_model
    ActName.new(email: current_user.email)
  end
```

**Comment by tfausak** [comment]
I think that would work if you wanted to default the value in the form to the current user's email. I thought you were asking about defaulting the value in the interaction, which is slightly different. But yeah, that's a good way to accomplish the former! In fact, it might be the only (reasonable) way.

**Comment by shanly** [comment]
The `to_model` guess did not default form for me - thats why I ended up doing the logic in the call to `CreateActName.new`.

I've now changed to below, which works - thanks.

```ruby
  object :current_user, class: User

  string :name

  string :email,
         default: -> { current_user.email }

  string :phone,
         default: -> { current_user.phone }
```
