### ISSUE TITLE
Can't use :result as input

### ISSUE THREAD

**Issue by scorix** [orgsync/active_interaction#375]
It conflicts with the instance method `:result`

```
class Foo < ActiveInteraction::Base
  string :result

  def execute
    {}
  end
end

Foo.run! result: "bar"

# => ActiveInteraction::InvalidInteractionError: Result is not a valid string
from /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/active_interaction-3.2.0/lib/active_interaction/concerns/runnable.rb:98:in `run!'
```

**Comment by AaronLasseigne** [comment]
The return from an interaction mimics an ActiveModel which means your filters are added as attributes. We use `result` for the return value of `execute`. This means it ends up being a reserved filter name.

In the `run!` version it's less clear but let's say you use `result` as a filter name and call `run`. The returned object would overwrite your given value with the return of `execute`.

Sorry but you'll have to pick another name.

**Comment by tfausak** [comment]
We could make `result` a reserved filter name in [the input processor](https://github.com/orgsync/active_interaction/blob/v3.2.0/lib/active_interaction/modules/input_processor.rb#L15). That way you'd get an error when you define the interaction rather than when you use it.

**Comment by tfausak** [comment]
There are quite a few filter names that are de facto reserved.

``` rb
Class.new(ActiveInteraction::Base) { boolean :errors }.run
# NoMethodError: undefined method `clear' for nil:NilClass

Class.new(ActiveInteraction::Base) { boolean :inputs }.run
# NoMethodError: undefined method `[]' for nil:NilClass

Class.new(ActiveInteraction::Base) { boolean :process_inputs }.run
# ArgumentError: wrong number of arguments (given 1, expected 0)
```

And so on. Pretty much any instance method defined on `ActiveInteraction::Base` should not be allowed as a filter name. Many of them aren't as catastrophic as `result`, but still lead to weird behavior. 

``` rb
class Example < ActiveInteraction::Base
  boolean :to_s
  def execute; end
end

Example.run(to_s: true).to_s
# => true
```

We could explicitly disallow these filter names, but the only thing that gets us is better error messages. Is that worth it?

**Comment by AaronLasseigne** [comment]
I think clear errors are useful.

**Comment by AaronLasseigne** [comment]
I'll knock this out sometime this week.
