### ISSUE TITLE
Rails 5 ActionController::Parameters no longer inherits from Hash

### ISSUE THREAD

**Issue by scarhand** [orgsync/active_interaction#381]
In Rails 5 ActionController::Parameters no longer inherits from Hash.

Therefor something like `MyInteraction.run(params)` will fail with the ArgumentError ["inputs must be a hash"](https://github.com/orgsync/active_interaction/blob/master/lib/active_interaction/base.rb#L172).

**Comment by tfausak** [comment]
This is pretty similar to #379. There are a few workarounds in there. The easiest fix is to use `params.to_unsafe_h`. But perhaps we need a better story for this. What do you think, @AaronLasseigne?

**Comment by scarhand** [comment]
@tfausak yeah, that's the fix I'm using right now. Even if you decide not to fix this, it would be nice if the documentation would make notice of the workaround.

**Comment by AaronLasseigne** [comment]
This might be a big enough problem to warrant a fix. If not then we definitely should do as @scarhand suggests and update the docs.

We could check for this one specific class name and convert it rather than implementing a generic `to_h` (which I agree is not good).
