### ISSUE TITLE
How to rollback transaction when using compose

### ISSUE THREAD

**Issue by lulalala** [orgsync/active_interaction#384]
Is it possible to rollback if I use `compose` and outcome is invalid?

```
def execute
  Foo.transaction do
    compose(A)
    compose(B)
    raise ActiveRecord::Rollback if invalid?
  end
end
```

Currently `compose` would throw us out of the transaction when outcome is invalid, thus not rolling  back.

My work around is to have a variation of `compose`, so execution continues. 

```
    def compose_without_throw(other, *args)
      outcome = other.run(*args)

      unless outcome.valid?
        errors.merge!(outcome.errors)
      end

      outcome.result
    end
```

Oh and thanks for the hard work! I met you at lunch in RubyKaigi last month :)

**Comment by AaronLasseigne** [comment]
Yup, I remember you. 😃 

I switched the code a while back from `raise` to `throw` because it's faster and it seemed more appropriate because I was thinking of this as an internal trigger inside the gem. I didn't account for the fact that it would not work with transactions.

It seems like the prudent thing to do is switch that back.

**Comment by tfausak** [comment]
Yeah, sounds like we should revert #326. I didn't think of transactions at the time.

**Comment by lulalala** [comment]
Just thow in some idea: would having both `compose` and `compose!` be a good idea? the ! would raise error.

**Comment by AaronLasseigne** [comment]
I think we can just throw the error. I don't think this is something the user needs to concern themselves with. It should just work. I have a fix, I'm just working on writing a test for it. It should be out soon.

**Comment by lulalala** [comment]
Thanks!
