### ISSUE TITLE
Local variables that have the same name as an input

### ISSUE THREAD

**Issue by ngan** [orgsync/active_interaction#395]
I sometimes have something like this:

```ruby
class CreateTransaction < ActiveInteraction::Base
  object :transaction

  def execute
    transaction = transaction.lock!
    # ...

   return transaction
  end
end
```
Note: I know that there exists a `with_lock` method that reloads the current instance of the `transaction` object, but this is a simplified example. In the real world scenario I sometimes need to lock multiple rows across multiple tables (with SQL joins) and in that case I have to overwrite the variable.

Anyways, back the point. When you assign a local variable shares the same as an input, things get really funking. I think it's because `transaction=` is define by AI::Base wherein it perform the coercion? Is there a (nice) workaround for this other than renaming the variable?

**Comment by tfausak** [comment]
Great question! I I don't think I've ever encountered this problem, so I don't have a solution off the top of my head. In general I try to think of the interaction inputs as immutable constants. 

ActiveInteraction does [define `attr_accessor`](https://github.com/orgsync/active_interaction/blob/v3.4.0/lib/active_interaction/base.rb#L155) for each input. It doesn't do any coercion there, though. You should be able to freely re-assign values in your `execute` block. What exactly is the problem you're hitting?

**Comment by ngan** [comment]
I can't remember what happens exactly on re-assignment...but I think I understand (and like) your concept of:
> In general I try to think of the interaction inputs as immutable constants.

**Comment by ixio** [comment]
If anyone else has this question, for example if you wanted to use `||=` to set a default at runtime, the problem comes from https://docs.ruby-lang.org/en/2.5.0/syntax/assignment_rdoc.html#label-Local+Variables+and+Methods.

A simple way to fix this is to use the '@' sign.

```ruby
class WontWork < ActiveInteraction::Base
  string :a, default: nil
  def execute
    a ||= 'default'
  end
end

class WillWork < ActiveInteraction::Base
  string :a, default: nil
  def execute
    @a ||= 'default'
  end
end

WontWork.run!            # "default"
WontWork.run!(a: 'test') # "default"
WillWork.run!            # "default"
WillWork.run!(a: 'test') # "test"
```
