### ISSUE TITLE
Non-nested hash inputs

### ISSUE THREAD

**Issue by ngan** [orgsync/active_interaction#396]
Just realized that when I declare a hash input where I don't know and am willing to accept all keys, I have to add `strip: false` to the declaration:

```ruby
hash :payload, strip: false
```

I was a little surprised because doesn't that mean:
```ruby
hash :payload
```
...Isn't very useful/practical at all?

Would it make sense to default to `strip: false` for non-nested hash declarations?

**Comment by tfausak** [comment]
ActiveInteraction tries to be safe by default. We *could* check the `hash` filter to see if it has a block attached and set `strip: false` if it doesn't. That would let you pass anything into the interaction, which kind of misses the point of using an interaction in the first place.

**Comment by tfausak** [comment]
I am going to close this. ActiveInteraction is working as intended. When you define a hash input, you must either explicitly list what will be in it or explicitly allow anything.
