### ISSUE TITLE
Two way mapping of filters with objects attributes

### ISSUE THREAD

**Issue by dmitry** [orgsync/active_interaction#397]
I believe it's an often practice to map fields from the objects, and backwards, especially when object is already exists and requires some updates.

Why not to embed some mechanism into the core to make that mapping automatic?

Allow to map the following cases:

- objects from filters, especially helpful to incapsulate logic outside `execute` method;
- filters from objects attributes - helpful to propogate data into the interaction filters, on `edit` forms;
- additionally could be especially handy to map errors messages from the object records.

Lets discuss about the pros/cons and other questions that come to head.

**Comment by tfausak** [comment]
I'm sorry, I don't think I understand what you're asking. Can you provide some concrete examples?

**Comment by dmitry** [comment]
For example, I have a `product` and `client` record models that I'm passing to the interaction as objects.

Product belongs to a client, and autosaves client when it's assigned to a product record.

I would like to create a product, along with a client profile (that I yet don't have in a system). 

```
class CreateProductInteraction < ActiveInteraction::Base
  object :product
  object :client

  string :product_name
  string :client_name

  def execute
    # assign attributes at objects from filters fields
    product.name = product_name
    client.name = client_name
    unless product.save
      # map errors messages from the object records
      errors.add(:product_name, product.errors[:name]) if product.errors[:name].present?
      errors.add(:client_name, client.errors[:name]) if product.errors[:name].present?
    end
  end
end

record = CreateProductInteraction.new(product: Product.new, client: Client.new)
record.run
```

At the moment you have to assign attributes of objects and map error messages.
It's very common way of working with interactions, that could be solved with mapping of objects to a fields.

Another example is when product and client are already created, and should be mapped to a interaction filters.

I could do a proposal, but first of all I would like to discuss what cons/pros of this method (for sure it should be an optional), and could be be merged into the core at all?!

**Comment by tfausak** [comment]
This sounds a little like #245. I see the repetition that you're trying to abstract. I don't know how to abstract it in a way that actually makes things better. If you could write that interaction any way you wanted, how would it look?

**Comment by dmitry** [comment]
It could be something similar: https://github.com/ismasan/hash_mapper

**Comment by tfausak** [comment]
Is there a problem with using hash_mapper inside your interaction? 

Again, I understand the problem you're facing. I don't know how to provide an abstraction for it that actually makes things easier. Plus if such an abstraction existed, it would make modifying the behavior of the interaction harder. For instance, how would your example change if it needed to say `client.name = client_name.strip.presence` instead?

**Comment by dmitry** [comment]
@tfausak `hash_mapper` works only with a Hashes, not with the objects. Additionally I would like to embed similar idea into the core, as `hash_mapper` lacks some additional features.

>  I don't know how to provide an abstraction for it that actually makes things easier.

That's the thing, I would like to discuss first regarding the most probable use cases, and then find the solution for them.

> Plus if such an abstraction existed, it would make modifying the behavior of the interaction harder.

Don't see why it would be harder, if the abstraction will be properly made.

Except from the example you gave: `client.name = client_name.strip.presence`, there could be also be a mapping with a multiple fields: `product.name = "#{client_name} #{product_name}"`.

At the first glace I thought it would be good to do something like this (but I'm still accumulating all the probable use cases):

```ruby
class CreateProductInteraction < ActiveInteraction::Base
  object :product
  object :client

  string :product_name, to: ['product.name', -> to { [client_name, to].join(' ') }]
  string :client_name, to: ['client.name', -> to { to.strip.presence }]

  def execute
    # it could assign only to the `client` object `assign_to(:client)`
    assign_to
    unless product.save
      map_errors
    end
  end
end

record = CreateProductInteraction.new(product: Product.new, client: Client.new)
record.run
```

**Comment by tfausak** [comment]
I feel like this just moves the business logic out of `execute`. It would also make the API that ActiveInteraction provides a lot bigger. And for what? A very slight reduction in the amount of code you need to write? I don't think it's worth it. 

And to continue on this example, you're now assigning `client_name.strip.presence` to `client.name`, but you're using the raw `client_name` in `product.name`. That's not what I would want, but fixing it would require duplicating that code or refactoring the entire interaction or adding another feature to this "object mapper" concept. 

Ultimately this isn't something I want to add to ActiveInteraction. I'm curious to hear what @AaronLasseigne thinks about it.
