### ISSUE TITLE
ActiveJob support

### ISSUE THREAD

**Issue by antulik** [orgsync/active_interaction#403]
This is for the reference to help people find answers.

I've created new gem `active_interaction-active_job` which adds ActiveJob support to active_interaction gem. 

[View github page](https://github.com/antulik/active_interaction-active_job)

Please post anything related to the new gem at the link above.

**Comment by tfausak** [comment]
See also #359.

**Comment by lulalala** [comment]
@antulik I see that you archived the gem, and am curious to know why. Thanks.
