### ISSUE TITLE
Add support of strict errors

### ISSUE THREAD

**Issue by antulik** [orgsync/active_interaction#406]
Would be nice if active_interaction could handle strict errors. 

For example:

```ruby
errors.add :passenger_count, 'This trip has no seats available', strict: true
```

`strict` mode throws `ActiveModel::StrictValidationFailed` exception. It is very useful when you want to stop any further validations.

alternative would be to add `return if errors.any?` after each "strict" validation.

Thoughts?

**Comment by antulik** [comment]
After looking at the internals of active_model/errors.rb, there is no easy way to make it work, so I guess the best is to advise not to use 'strict' mode at all.

**Comment by tfausak** [comment]
Interesting. I haven't heard of strict errors before. In this scenario I usually do `return errors.add :something`. Unfortunately that only works if you're in `execute` (and not in a proc). 

I'm not sure I understand how `strict` currently behaves based on your explanation. Are you saying it throws `ActiveModel::StrictValidationFailed`? If that's the case, the interaction should ignore the error and it will bubble up through your stack. I can see how that is unexpected, but everything's doing exactly what it said it would do. 

If we wanted to handle this, it seems like the right place to do so is in [`ActiveInteraction::Runnable#run`](https://github.com/orgsync/active_interaction/blob/v3.4.0/lib/active_interaction/concerns/runnable.rb#L80).

**Comment by antulik** [comment]
@tfausak  instead of adding error to the `errors` object `:strict` mode raises it as the exception. However the exception is missing the field's data, so it's impossible to accurately rescue exception and append info back to `errors` object.

As you've said `return errors.add :something` only works inside `execute`, which is not always the case.

My expectation that the interaction object `run` method always returns outcome object with errors. And `strict` mode breaks that expectation. 

While I think there is no easy way to support strict mode, I feel there is a good use case for halting execution if there are errors. (see my workaround above) @tfausak would you like a separate issue for it?

**Comment by AaronLasseigne** [comment]
I was able to get `:strict` to work as expected in both uses of validation on an `ActiveInteraction::Base` object.

On `validates`:
```ruby
> class I < ActiveInteraction::Base
>   integer :i
>   validates :i, numericality: { greater_than: 5 }, strict: true
>   def execute; puts i; end
> end
=> :execute
> o = I.run(i: 2)
ActiveModel::StrictValidationFailed: I must be greater than 5
```

On `errors.add`:
```ruby
> class I < ActiveInteraction::Base
>   integer :i
>   def execute; errors.add(:i, :invalid, strict: true); end
> end
=> :execute
> o = I.run(i: 1)
ActiveModel::StrictValidationFailed: I is invalid
```

We haven't re-implemented the errors. We use the existing `ActiveModel::Errors` module so anything it can do we should (in theory) be able to do.

**Comment by AaronLasseigne** [comment]
I'm going to close this. If I'm missing something or didn't understand please let me know.
