### ISSUE TITLE
Is there a way to determine whether a hash's key was given?

### ISSUE THREAD

**Issue by cloudrave** [orgsync/active_interaction#408]
I'm allowing `nil` as an input for any of these, but I also want to know whether someone specified `nil` or whether it's just the default because the key was unspecified.  That's fine when we're not dealing with a hash, but when we are, I seem to be running into issues.

```ruby
  hash :attributes, default: {} do
    string :description, default: nil
    string :location, default: nil
  end
```

I know that I can determine whether `attributes` was passed by asking `given? :attributes`, but how can I determine whether `attributes[:description]` was given?

Thank you for a wonderful gem!  The interaction pattern really makes Rails shine!

**Comment by cloudrave** [comment]
Inspecting the code, it seems that the relevant line is [here](https://github.com/orgsync/active_interaction/blob/60023aacaae3b1b8da8bf7f01d74dabf24627f2f/lib/active_interaction/base.rb#L253).
```ruby
    @_interaction_keys = inputs.keys.to_set & self.class.filters.keys
```

This seems to imply that the feature I'm hoping for does not exist.  Maybe I'm missing a way around this though.  Any thoughts?

Thanks!

**Comment by tfausak** [comment]
You're right, we don't currently support this.

**Comment by AaronLasseigne** [comment]
I feel like this makes sense to add. We could allow `given?` to take multiple arguments so that it works like `dig`. If we do that would we want to support checking Array slots or only hash keys?

**Comment by tfausak** [comment]
I had not heard of `dig` before. It's new in Ruby 2.3. We could add support by requiring or copying [ruby_dig](https://github.com/Invoca/ruby_dig). Seems like we should support array indices as well as hash keys.

**Comment by cloudrave** [comment]
That seems like a really intuitive solution to me.  I'm not sure how array indices could not be 'given' if they existed, but I only just starting using Ruby.

**Comment by AaronLasseigne** [comment]
It seems like we all think this is a good direction. I should be able to build this out later this week when I've got some time.
