### ISSUE TITLE
String Filter doesn't convert field values to strings automatically

### ISSUE THREAD

**Issue by kraytruthg** [orgsync/active_interaction#413]
Hi there,

I run into a problem with `String` filter.
Let's say for `User` model, we have a `string` column called `age`.

We can do it in rails:
```
 User.create(age: 21)
```

But we can't do the same thing with interaction
```
class UserCreate < ActiveInteraction::Base
  string :age

  def execute
    User.create(age: age)
  end
end

UserCreate.run(age: 21).errors.messages
=> {:age=>["is not a valid string"]}
```

How do you think about adding auto cast feature to String filter?

**Comment by AaronLasseigne** [comment]
In this case why wouldn't you use an `integer` filter?

**Comment by kraytruthg** [comment]
Let's say we want to create a record from params.
``` ruby
class Listing < ActiveRecord::Base
  connection.create_table :listings, force: true do |t|
    t.string :listing_type
  end
end

class CreateListing < ActiveInteraction::Base
  string :listing_type

  def execute
    Listing.create(listing_type: listing_type)
  end
end
```

However, the params `listing_type` sent from JSON request is integers; while the params `listing_type` sent from the web form is strings.
In this case, `CreateListing.run(params)` would raise error.

Since `integer` filter does convert the input to integers, I wonder why `string` filter doesn't convert the input to strings.

**Comment by AaronLasseigne** [comment]
Converting between types can get tricky. The only reason we convert from strings into other types is that strings rule the world. All the params from the web request will be strings. Not handling strings would make everything incredibly painful. You'd have to convert everything yourself. Outside of that we've taken the trade-off of safety over convenience. You won't accidentally pass an array to a string input and get some crazy outcome.

**Comment by kraytruthg** [comment]
@AaronLasseigne , thanks for the explanation. 👍
