### ISSUE TITLE
ActiveInteraction::InvalidValueError: :format

### ISSUE THREAD

**Issue by IvanKhoteev** [orgsync/active_interaction#415]
I have a problem when try to pass params in interaction and params object which contains key :format
Rails automatically adds this key/value pair in part of requests

I tried to reproduce this error as wrote below:

I take example from documentation
```
class Square < ActiveInteraction::Base
  float :x

  def execute
    x**2
  end
end
```

And then I pass :format key in *run* method I get this error too

```
2.4.1 :001 > Square.run(x: 123, format: 'json')
ActiveInteraction::InvalidValueError: :format
	from (irb):1
```
In examples uses Rails v 5.1.0 and ActiveInteraction v 3.5

**Comment by AaronLasseigne** [comment]
fixed by 40a02f428affb0e351aa9620eda10e63de691b50 and released in 3.5.1

Thanks for the detailed ticket.
