### ISSUE TITLE
 errors.merge! inception

### ISSUE THREAD

**Issue by dritir** [orgsync/active_interaction#417]
Hello, I don't know if this is the expected behaviour or not but this is the situation:

I have 2 interactions, the inner one with:
` errors.add(:base, :blank)`
the outer one with:
```
errors.add(:base, :wrong_number)
errors.merge!(inner_output.errors)
```

If I call the errors for the outer:
`outer_output.errors.details`
I will get this hash:
`{:base=>[{:error=>:wrong_number}, {:error=>"cannot be blank"}]} `
meaning its merging the translated message and not the symbol from the inner interaction.

Is this how its supposed to be?

**Comment by AaronLasseigne** [comment]
This has been fixed as released as 3.5.2. Thanks for reporting it!
