### ISSUE TITLE
Idea: Class level attribute defaults

### ISSUE THREAD

**Issue by antulik** [orgsync/active_interaction#418]
Some thoughts on the feature which might be useful. The idea is to have class level defaults for the attributes. For example: 

```ruby
class Add < ActiveInteraction::Base
  integer :a, :b

  def execute
    a + b
  end
end

Add.defaults.a = 1
Add.run!(b: 2) 
# => 3
```

### Dependency injection

Interaction can pre list class dependencies. That's handy because the interaction class becomes loosely coupled and you don't need to pass big list of classes to use every time you call it.

### Testing

With dependency injection it's particular useful in testing, when you can swap classes without stubbing used classes or the interaction itself.

**Comment by antulik** [comment]
There is a work around which currently works

```ruby
class Add < ActiveInteraction::Base
  integer :a, :b

  def execute
    a + b
  end
end

Add.filters[:a].options[:default] = 1
Add.run!(b: 2)
# => 3
```

That works, it would overwrite the attribute default and it's not possible to unset it. Keen to see what other people think and if such pattern should be promoted more.

**Comment by AaronLasseigne** [comment]
If you're wanting to pass in common attributes (for tests and such) you can put those in a hash and merge into that hash as needed.

```ruby
defaults = {a: 1}

Add.run!(a.merge(b: 2))
```

We do something like that in our own tests.

```ruby
let(:inputs) { {a: 1} }
let(:result) { Add.run!(inputs) }

describe 'foo' do
  before { inputs[:b] = 2 }
  
  it 'works' do
    expect(result).to eql 3
  end
end

**Comment by antulik** [comment]
good idea, I think this issue could be closed as there are plenty of work arounds. But if anybody is keen on dependency injection feature, it would be great to hear those.
