### ISSUE TITLE
if you do not input an integer attribute, I do not want to be invalid type error

### ISSUE THREAD

**Issue by kbaba1001** [orgsync/active_interaction#421]
If you do not input an integer attribute in form, it becomes invalid type error.
I want to process with varidations.

I use the string type instead, but is there a better way?

```ruby
class Interaction < ActiveInteraction::Base
  integer :x

  def execute
  end
end

# if you do not input "x" in form, it becomes params: {"x" => ""}.
Interaction.run!(x: '') #=> raise ActiveInteraction::InvalidInteractionError
```

**Comment by antulik** [comment]
That feature will be supported in 4.0.0
https://github.com/orgsync/active_interaction/issues/412#issuecomment-309156843

Until then I'm using a workaround:
```
# config/initializers/active_interaction.rb
module ConvertBlankToNil
  def convert(value, context)
    if value.blank?
      nil
    else
      super
    end
  end
end
ActiveInteraction::IntegerFilter.prepend(ConvertBlankToNil)
```

**Comment by kbaba1001** [comment]
@antulik Thunk You !!!

**Comment by AaronLasseigne** [comment]
@antulik is right (BTW, thanks for responding). I'm going to close this because of the work coming in #412.
